/**
 * Axe-Fx II agent guidance — migrated from the long device-namespaced
 * tool descriptions in `src/fractal/axe-fx-ii/tools/{discovery,params,
 * navigation,preset}.ts`.
 *
 * v0.3 removed the device-namespaced tool surface; the LLM no longer
 * sees these guidance blocks through tool descriptions. They surface
 * instead via `describe_device({ port: 'axe-fx-ii' }).agent_guidance`.
 */

export const AXEFX2_AGENT_GUIDANCE: Readonly<Record<string, string>> = {
  diagnostic_isolation: [
    'When the user reports an unwanted artifact in a tone, isolate via',
    'set_bypass: toggle one block at a time and ask the user to play',
    'between toggles, before changing any param values. The human-in-the-',
    'loop is the test signal. Bulk edits during diagnosis hide which',
    'change mattered; isolation surfaces the source one round-trip at a',
    'time. Batching is correct for confident builds; isolation is the',
    'right tool for chasing artifacts.',
  ].join(' '),

  channel_model: [
    'Axe-Fx II blocks expose two channels, X and Y, NOT the AM4 four',
    '(A/B/C/D). Scenes pick which channel each block uses (plus per-block',
    'bypass). When the user says "scene 2", that\'s a selector for per-',
    'block channel + bypass state within the current preset; it doesn\'t',
    'duplicate the params (channels hold the params, scenes pick which',
    'channel each block uses).',
  ].join(' '),

  preset_location_format: [
    'Axe-Fx II presets are addressed by integer slot index 0..16383 on',
    'the wire. The FRONT PANEL displays preset numbers as wire+1 (front-',
    'panel #1 is wire 0). The user usually thinks in front-panel numbers:',
    'pass the same integer the user names; describe_device reports the',
    'preset_location_format.',
  ].join(' '),

  param_addressing: [
    'Params are addressed by (block, name) where `block` resolves on',
    'block instance display name ("Amp 1", "Delay 1") OR effectId',
    'integer, and `name` is the snake-case param key (effect_type, gain,',
    'mix, etc.). All instances of the same block group (e.g. Amp 1 / Amp',
    '2) share the same param table; list_params per group covers every',
    'instance.',
  ].join(' '),

  set_param_interpret: [
    'Numeric set_param values are interpreted in display units by default.',
    'For wire-level writes (raw 0..65534), some param types lack a',
    'calibrated display range and the unified set_param accepts the wire',
    'integer directly; see list_params for the param\'s controlType.',
    'Enum / select params accept the display name string OR the wire',
    'index. The relaxed matcher disambiguates partial names; the ack',
    'reports the full resolved name in parentheses.',
  ].join(' '),

  tempo_time_discipline: [
    'IMPORTANT for delay / chorus / flanger / phaser / tremolo: each of these',
    'blocks has a `tempo` enum (NONE plus musical divisions 1/64..1/2..1..4).',
    'When `tempo` is anything other than NONE, the Axe-Fx II LOCKS the block\'s',
    'timing param to (song tempo x division) and SILENTLY IGNORES absolute',
    'writes to that timing param. The locked param is `delay.time` for delay',
    'and `rate` for chorus / flanger / phaser / tremolo. Read the `tempo` value',
    'alongside time/rate before planning a change so you know which side of the',
    'sync to write. When you DO need to write `time` or `rate` in absolute units,',
    'FIRST set the block\'s `tempo` to "NONE", otherwise the write is silently',
    'overridden. Order: (1) set tempo to "NONE", (2) write time/rate. Setting',
    'tempo to a division does not require clearing time/rate first; the device',
    'just stops reading it. This is per-channel: X and Y each carry their own',
    'tempo + time, so clear tempo on the channel you are editing.',
  ].join(' '),

  delay_tempo_default: [
    'For DELAY specifically: tempo-synced repeats are the PROFESSIONAL DEFAULT',
    'for guitarists in modern popular music. When the user asks for a delay tone',
    '(especially "ambient", "obvious", "rhythmic", "Edge / U2 style", "post-rock",',
    '"shoegaze", "worship", "atmospheric"), REACH FOR `delay.tempo` FIRST and pick',
    'a musical division: 1/4 DOT is the iconic Edge sound, 1/4 for clear rhythmic',
    'repeats, 1/2 DOT or 1/2 for ambient washes, 1/8 DOT for rhythmic urgency,',
    '1/8 for tighter syncopation. Fall back to absolute `delay.time` only when the',
    'user explicitly asks for a specific ms count, calls out free-time / rockabilly',
    '/ slapback, or is playing without a tempo reference.',
    'For MODULATION blocks (chorus / flanger / phaser): free-Hz `rate` is the',
    'typical default; these are textural, not rhythmic, and tempo sync rarely',
    'matches the ask. Tremolo is the exception: rhythmic chops (1/8 / 1/16 tempo)',
    'are common alongside vintage Hz-rate tremolo.',
  ].join(' '),

  loudness: [
    'LOUDNESS MODEL on the Axe-Fx II. All values are DISPLAY UNITS thanks',
    'to a calibration overlay on the unified set_param surface. "5" means',
    'midpoint of the knob, not wire integer 5. A common failure mode:',
    'writing `drive.volume: 5` thinking knob position 5 used to pass wire',
    '5 to the device and land near-mute. The overlay closes that.',
    '',
    'The knobs that move loudness, in roughly the order you should reach for',
    'them:',
    '',
    '  amp.input_drive   0..10 knob   INPUT drive into the amp model. Aliases:',
    '                                 `gain`, `drive`. Changes tone character',
    '                                 (breakup, compression). NOT a clean',
    '                                 volume knob.',
    '  amp.master_volume -80..+20 dB  Amp master output trim. Aliases: `master`.',
    '                                 Calibrated via the fractal-convention',
    '                                 dB suffix rule (0 dB is unity). Use this',
    '                                 for "make the amp louder / quieter".',
    '  amp.level         -80..+20 dB  Post-amp clean trim for preset-to-preset',
    '                                 matching. Same shape as master_volume',
    '                                 but downstream of the amp model.',
    '  drive.volume      0..10 knob   Output of the drive block. (Cross-device',
    '                                 note: AM4 calls this `drive.level`. III',
    '                                 calls it `drive.level`. The unified',
    '                                 alias table accepts `level` here.)',
    '  drive.mix         0..100 %     Wet/dry of the drive block. 100% is the',
    '                                 conventional setting for a pedal in',
    '                                 front of an amp.',
    '  cab.level         -80..+20 dB  Cab block output. Often the cleanest',
    '                                 spot to trim overall preset loudness',
    '                                 because the cab sits downstream of the',
    '                                 amp and most FX.',
    '  reverb.mix        0..100 %     Wet/dry. 25-40% is normal room/plate;',
    '                                 above 50% masks amp mid-range.',
    '  delay.mix         0..100 %     Wet/dry. 20-35% for rhythmic delays;',
    '                                 lower for subtle thickening.',
    '  <fx>.mix          0..100 %     Same shape on chorus / flanger /',
    '                                 phaser / rotary / tremolo / compressor.',
    '  output.level      -80..+20 dB  GLOBAL output trim (Output block, not',
    '                                 inside a preset). Use this for stage-',
    '                                 wide level only; every preset is',
    '                                 affected.',
    '',
    'CROSS-PARAM INTERACTIONS (audio-engineer rules of thumb):',
    '',
    '  - Raising amp.input_drive lifts perceived loudness as well as gain.',
    '    For "more crunch but same volume", raise input_drive by N and drop',
    '    amp.master_volume by roughly N/2 (where N is in knob 0..10 steps).',
    '  - Engaging a drive block in front of an amp typically adds 3-6 dB',
    '    even at unity drive.volume. Expect to drop amp.master_volume or',
    '    cab.level 2-3 dB when adding a drive to keep stage level steady.',
    '  - Reverb mix above 50% will mask 1-3 kHz mid-range. If the user',
    '    reports "the lead lost its bite after reverb", pull reverb.mix',
    '    back to 25-35%.',
    '  - Vox AC30 family and non-master Marshall lineages (Plexi 100W,',
    '    1959SLP, 1987X) do not expose amp.master_volume; the wire write',
    '    acks but the value is silently ignored. On those lineages,',
    '    amp.level or cab.level is the only clean loudness control.',
    '',
    'CROSS-DEVICE NAMING. Same conceptual knob, different canonical names:',
    '',
    '  Axe-Fx II drive.volume        ↔  AM4 drive.level        ↔  Axe-Fx III drive.level',
    '  Axe-Fx II amp.master_volume   ↔  AM4 amp.master         ↔  Axe-Fx III amp.master',
    '  Axe-Fx II amp.input_drive     ↔  AM4 amp.gain           ↔  Axe-Fx III amp.gain',
    '',
    'The unified surface ships a cross-device alias table at',
    'packages/core/src/protocol-generic/cross-device-aliases.ts. An agent',
    'trained on AM4 vocabulary can type `drive.level` on the II and the',
    'dispatcher resolves it to `drive.volume`. Prefer the canonical II name',
    'when writing, and quote the canonical name back in summaries.',
    '',
    'LEVELING — UNITY MATCH (Fractal\'s own published philosophy, confirmed',
    'against the Fractal wiki + forum). The DEFAULT is UNITY: balance every',
    'scene and every preset so its AVERAGE signal sits on the WHITE LINE (0 dB)',
    'of the Output block Internal Levels Meter. That 0 dB line is the sweet',
    'spot — strong signal with ample headroom. RED IS NOT CLIPPING: the meter',
    'is calibrated with ~12 dB of headroom at the red line (OUT knob at max),',
    'so brief peaks above the white line are fine. Match the AVERAGE, not the',
    'peaks, then confirm by ear.',
    '',
    'GAIN IS A LOUDNESS CONTROL IN DISGUISE. Distortion raises average power, so',
    'a clean low-gain scene meters FAR BELOW a saturated high-gain scene at the',
    'same level/master. Set amp.input_drive / master_volume / drive / mix for',
    'TONE first, expect the scenes to diverge in metered loudness, then',
    'neutralize the difference with output.scene_N_main. The common mistake',
    '(and what the old guidance wrongly encoded as "clean -3 dB") is making the',
    'clean scene QUIETER — it is already the quietest. A clean scene typically',
    'needs a POSITIVE trim of +6..+12 dB relative to the high-gain scenes as a',
    'starting point.',
    '',
    'PRIMARY SCENE-BALANCE CONTROL: output.scene_1_main .. output.scene_8_main',
    '(±20 dB each). These are the II\'s purpose-built per-scene Main levels (the',
    '"Scene Levels" feature on the Output block) — the direct analog of the',
    'AM4\'s preset.scene_N_level, one per scene (the II has 8). They are',
    'post-chain, change no tone, and need NO channel switch, so they are both',
    'the right tool AND the most reliable to write. Reach for output.scene_N_main',
    'FIRST to match scenes; the II actually has MORE per-scene level headroom',
    'than the AM4, not less.',
    '  amp.level / cab.level   secondary, per-channel trims — useful when you',
    '                          want the trim tied to a specific amp/cab channel.',
    '                          They need a channel switch (which can drop an ack),',
    '                          so prefer output.scene_N_main for plain scene',
    '                          matching. NOT amp.master_volume (it interacts with',
    '                          the amp model and changes tone).',
    '  output.level            the GLOBAL Main output trim (one value, every',
    '                          scene) — stage-wide level only, NOT per-scene.',
    'A solo scene may sit ~+3 dB above unity (the documented solo lift); set it',
    'on that scene\'s output.scene_N_main. Everything else defaults to unity.',
    '',
    'THE AGENT CANNOT READ THE METER OVER MIDI. After any multi-scene build, set',
    'starting trims from the heuristics above, then LABEL THEM UNVERIFIED, point',
    'the player at the Output block levels meter (white line = unity), have them',
    'play each scene and report where each average sits, and trim from there.',
    'The human meter read is the test signal — same human-in-the-loop pattern',
    'as bypass isolation.',
    '',
    'BAKE LEVELS INTO THE FIRST APPLY; DO NOT LOOP get_param TO CHECK LOUDNESS.',
    'Compute the starting estimates (per-amp offset + the clean +6..+12 gain',
    'compensation) WHILE planning and put output.scene_N_main (one per scene)',
    'in the apply_preset call so the preset lands roughly balanced in ONE call.',
    'get_param CANNOT verify loudness — it echoes the value you wrote, not the',
    'meter — so a get->set->get loop is wasted round-trips that burn the tool',
    'budget. Set estimates, label them unverified, STOP, and ask the player for',
    'the meter; apply at most ONE correction per report. Never iterate blind.',
    '',
    'PER-AMP LOUDNESS OFFSETS. Different amp models meter at different loudness',
    'at the same master/level. The per-amp dB offset is surfaced on the enum',
    'table:',
    '  list_params({port:"axe-fx-ii", block:["amp"], name:["type"]}).params[0]',
    '      .enum_value_loudness_offsets_db',
    'a map of amp model label -> dB offset vs the reference amp (Twin Reverb at',
    'master=6 = 0 dB). Same field on drive.type for boost offsets (T808 OD at',
    'level=7 = +6 dB reference). Apply it as a starting correction. If an amp',
    'you used has NO entry, treat the offset as UNKNOWN and SAY SO ("offset',
    'unknown, verify by meter") — do NOT silently assume 0 dB reference, which',
    'is how an unbalanced build slips through.',
    '',
    'COMMON FAILURE. Writing `drive.volume: 5` expecting unity-knob',
    'position can land near-mute on older firmware paths where the wire',
    'is interpreted as raw integer 5. The display calibration on the',
    'unified surface closes this for known knobs, but when in doubt about',
    'a param\'s display range, call list_params({port:"axe-fx-ii",',
    'block:"<name>"}). The response carries display_min / display_max /',
    'unit per param. After any loudness write, confirm with get_param.',
  ].join('\n'),

  lineage_matchvia: [
    'lookup_lineage returns a `matchVia` field naming the lookup-path',
    'used to find the wiki entry (NOT a confidence rating on the data):',
    '  direct         : exact name match. Trust the data.',
    '  abbrev-expand  : Axe-Fx II truncates words to fit its 16-char',
    '                   display ("NRML"→"NORMAL", "MDRN"→"MODERN").',
    '                   Same model, different label. Trust the data.',
    '  reverb-swap    : reverb labels invert word order ("MEDIUM HALL"',
    '                   matches wiki "Hall, Medium"). Trust the data.',
    '  prefix         : Axe-Fx II uses a family-head abbreviation that',
    '                   prefixes a more specific wiki entry. Family-',
    '                   level lineage is solid; specifics approximate.',
    '  unmatched      : no wiki record. Model exists in firmware, but',
    '                   lineage prose isn\'t sourced.',
    'Do NOT hedge on direct / abbrev-expand / reverb-swap; those are',
    'known-good display-string conventions. Hedge only on prefix /',
    'unmatched, or when the record\'s `flags` array surfaces a substantive',
    'data-quality issue (cross-attributed forum quotes, inherited basedOn).',
  ].join(' '),

  lineage_flags: [
    'Substantive lineage flags to surface to the user:',
    '  INHERITED: basedOn / tubes / cab were back-filled from a sibling',
    '    amp record. For amp-family siblings (Plexi 50W Normal/High) this',
    '    is fine; for non-sibling inheritance basedOn might be wrong.',
    '  Forum quotes naming a different amp family than the record: known',
    '    AM4 wiki-parser bug where cross-cutting "Regarding the following',
    '    X models" prose attaches to the prior entry. Filter; don\'t',
    '    surface as authoritative.',
    'Block coverage: amp (259 enum / 196 matched), drive (36 / 34),',
    'reverb (43 / 25), delay (18 / 17). Compressor / chorus / flanger /',
    'phaser / wah are AM4-only for now.',
  ].join(' '),

  lineage_batching: [
    'lookup_lineage `name` is ALWAYS an array. Multi-amp/multi-drive',
    'scene builds (clean reference + drive amp, A-channel drive +',
    'B-channel drive) should pass every name in ONE call:',
    '  lookup_lineage({port:"axe-fx-ii", block_type:"amp",',
    '                  name:["USA IIC+","Deluxe Verb Normal"]})',
    'Returns {entries:[...]} with loudness per entry. Two sequential',
    'calls cost you a turn each; one batched call costs one turn.',
  ].join(' '),

  save_intent_required: [
    'SAVE INTENT REQUIRED: call save / persist tools (apply_preset with',
    'target_location, save_preset) ONLY when the user has explicitly asked',
    'to save / persist / store / keep the preset. apply_preset without',
    'target_location is reversible (switch presets to discard); save is',
    'not. When in doubt, apply without target_location and ask whether to',
    'persist.',
  ].join(' '),

  apply_preset_fresh_vs_tweak: [
    'TWEAK vs FRESH: apply_preset REPLACES the working-buffer layout. If',
    'the user says "tweak my current tone", call set_param / set_block /',
    'set_bypass for the targeted change instead. apply_preset is for fresh',
    'designs ("build me a clean tone").',
  ].join(' '),

  recipe_usage: [
    'RECIPE PICKUP: when the user names a recognizable tone family',
    '("U2 Edge dotted-eighth", "thrash metal Master of Puppets", "Texas blues',
    'crunch", "djent"), scan describe_device(port).recipes[] for a block_stack',
    'entry whose description matches. If you find one, you MUST apply via',
    'apply_preset({port, recipe_id: "<id>"}) , NOT by pasting slots manually.',
    'The slim summary deliberately omits the recipe\'s knob values; pasting',
    'manually means improvising those values and hitting enum / range',
    'validation errors. Use the `overrides` arg for targeted knob tweaks',
    '(e.g. swap the amp for a Recto). Recipes are hand-curated from',
    'documented player rigs (Premier Guitar rig rundowns, Sound on Sound',
    'features) , a better starting point than improvised knobs.',
    'The response\'s `applied_spec` field echoes the RESOLVED INPUT (recipe +',
    'overrides), NOT a device readback. It confirms what was sent, not what',
    'landed. For post-write verification, call get_preset.',
    'Single-block recipes (auto_wah, pitch, wah, filter, scene_leveling)',
    'are different: they ship inline params in describe_device.recipes[]',
    'and apply via set_block + set_params on the target block , recipe_id',
    'is block_stack-only.',
  ].join(' '),

  state_anchoring: [
    'STATE ANCHORING (read-before-write). When the user references current',
    'state ("make it warmer", "less of that", "match my Sunday Morning tone"),',
    'call get_preset({port:"axe-fx-ii"}) FIRST to snapshot the active working',
    'buffer in one tool call. Latency is ~400 ms on Q8.02 for an 11-block',
    'preset (live-measured); larger or denser presets may push toward 1 s.',
    'Generally fast enough not to need an upfront wait note. Summarise what',
    'is placed before proposing changes, since the user can\'t see the wire',
    'and may not know which scene or channel is active.',
    '',
    'RESPONSE SHAPE. The snapshot describes the ACTIVE SCENE only.',
    'Each slot carries: block_type, instance, id (canonical block id for',
    'scene maps and routing refs), bypassed (boolean), and per-channel',
    'params. By default the ACTIVE channel is nested under params_by_channel',
    '({X} or {Y}) with channel_status:"active" , this keeps get_preset fast',
    '(~400 ms, active-channel fn 0x1F dump plus the fn 0x0E state map, zero',
    'extra round-trips). The inactive X/Y channel is NOT read by default. To',
    'also read it (full params_by_channel:{X,Y}, channel_status:',
    '"all_channels"), pass include_channel_state:true , this adds a per-param',
    'walk of the inactive channel and is much slower (tens of seconds on a',
    'dense preset), so only request it when you actually need both channels.',
    'Scenes 2..8 are NOT included; routing edges are NOT included.',
    '',
    'READ-MUTATE-WRITE PATTERN. To change a few knobs based on the snapshot,',
    'use set_param or set_params for the targeted writes. Do NOT feed the',
    'whole get_preset response back into apply_preset: apply_preset has',
    'FRESH-BUILD CLEARING semantics (unlisted slots clear to none, unlisted',
    'scenes reset to defaults). Feeding back a get_preset response would',
    'reset scenes 2..8 to defaults and drop any routing edges. The snapshot',
    'is for INSPECTION and TARGETED EDITS, not for cloning back wholesale.',
    '',
    'POST-WRITE VALIDATION. After set_param / set_params / apply_preset,',
    'call get_preset again and diff against your intent on the slots and',
    'params you wrote. Useful when a type-gated param silently no-ops (the',
    'wire ack does NOT mean audible change). Only compare the slots you',
    'mutated; the rest of the snapshot is for context, not assertion.',
    '',
    'WHEN NOT TO USE get_preset. Targeted single-param questions ("what is',
    'the gain right now?") run faster with get_param (~80 ms vs ~2 s). For',
    '2 to 5 specific knobs, use get_params. Use get_preset when you need',
    'the whole active-scene layout, not when you already know which knobs',
    'you care about.',
  ].join(' '),

  pitch_block: [
    'PITCH BLOCK: read this before building any harmonizer / detune /',
    'whammy / arpeggiator preset. The pitch block is the single most',
    'mode-dependent block on the Axe-Fx II and a naïve set_param sequence',
    'will silence the signal or pin the harmony to an unmusical extreme.',
    'Common failure: treating voice_1_harmony as a semitone offset in',
    'INTEL HARM mode produces an "extremely high" harmony (the param',
    'is a scale-degree index, not semitones, in that mode).',
    '',
    '== Effect-type choice ==',
    'pitch.effect_type picks the algorithm and decides what every other',
    'param means. The two harmonizer modes:',
    '  • FIXED HARM  : chromatic. voice_N_harmony is a semitone offset.',
    '                  Sounds parallel (always +3 semitones).',
    '  • INTEL HARM  : diatonic. voice_N_harmony is a SCALE DEGREE (1=',
    '                  unison, 3=third, 5=fifth, 7=seventh). Needs key +',
    '                  scale. This is what classic harmonized leads use',
    "                  (Maiden, Boston, 'Hotel California').",
    'For "harmony in E minor" the right answer is almost always INTEL HARM',
    'with key=E, scale="AEOLIAN MIN", voice_1_harmony=3 (display) which',
    "lands as wire 26 on Q8.02 firmware (the label echoes back as '3').",
    '',
    '== voice_N_harmony wire encoding (hardware-verified) ==',
    'The descriptor lists displayMin=0, displayMax=48, but the device',
    'treats this param as a near-direct integer index, NOT a linear',
    'scale across 0..65534. Hardware ground truth:',
    '  wire 24 → label "1"   (unison center)',
    '  wire 25 → label "2"   (+1 step)',
    '  wire 26 → label "3"   (+3 semitones, minor 3rd up in INTEL HARM)',
    '  wire 27 → label "4"',
    'Formula for the wire integer: `wire = 23 + scale_degree`.',
    'In INTEL HARM mode pass the display value as a small integer 1..N',
    'and the dispatcher\'s linear display→wire scaling lands you in the',
    'right ballpark for testing, but READ-BACK is required because the',
    'display calibration here is approximate. Pass display=3 and check',
    'get_param echoes label "3" before declaring success.',
    '',
    '== Voice 2 mute discipline ==',
    'voice_2_level defaults non-zero on most factory pitch presets. If',
    'you only want ONE harmony voice, explicitly set voice_2_level=0',
    '(wire 0 = 0%). Skipping this is the canonical cause of a dissonant',
    "minor-2nd clash the user didn't ask for.",
    '',
    '== Opaque-percent / opaque-dB params (mix, level, voice_N_level) ==',
    'These are `unit: "opaque"`: set_param writes the wire integer',
    'DIRECTLY, no display scaling. Cheat sheet from hardware-verified',
    'reads:',
    '  pitch.mix    wire 16384 = 25%    wire 32767 = 50%    wire 65534 = 100%',
    '  pitch.level  wire 32767 = -30 dB wire 49152 = -5 dB',
    '               wire 52428 ≈ 0 dB UNITY  wire 65534 = +20 dB',
    '  pitch.voice_N_level  wire 0 = 0% (muted)  wire 65534 = 100%',
    'Sending `value: 50` to pitch.mix sets it to 0.076 %, not 50 %, and',
    'sending `value: 0` to pitch.level mutes the entire block.',
    '',
    '== Typical harmonized-lead config (one-shot set_params payload) ==',
    'After apply_preset places the block:',
    '  pitch.effect_type   = "INTEL HARM"',
    '  pitch.key           = "E"  (or whatever)',
    '  pitch.scale         = "AEOLIAN MIN"  (or whatever)',
    '  pitch.voice_1_harmony = 3       // scale degree, READ BACK to verify',
    '  pitch.voice_2_level = 0         // wire 0 = mute the second voice',
    '  pitch.mix           = 32767     // wire 50% = 1:1 dry/wet',
    '  pitch.level         = 52428     // wire ≈ 0 dB unity gain',
  ].join('\n'),
};
