/**
 * Gen-3 (modern Fractal family) shared catalog types.
 *
 * `Param` is the row shape of every gen-3 device-true param catalog
 * (axe-fx-iii, fm3, fm9, vp4 — the fm3/fm9/vp4 catalogs are
 * AUTO-GENERATED by `scripts/_research/generate-modern-fractal-catalog.ts`
 * and import this type). The shape is shared; the catalog DATA is
 * device-specific — paramIds are never reused across model bytes.
 *
 * Moved verbatim from `axe-fx-iii/params.ts` (which re-exports both
 * types for compatibility).
 */

/**
 * Display-unit tag for a gen-3 family parameter.
 *
 * `'unverified'` is the default for entries the generator could
 * not infer (the AM4 has no matching parameter, or the III family
 * has no AM4 analog). Other tags are AM4-derived display
 * conventions — they describe the user-facing scale (dB, ms,
 * knob_0_10, etc.) but NOT the gen-3 wire encoding. Display↔wire
 * conversion is still the caller's responsibility
 * until hardware verification lands.
 */
export type Unit = 'bipolar_percent' | 'count' | 'db' | 'degrees' | 'enum' | 'hz' | 'knob_0_10' | 'knob_0_20' | 'ms' | 'numeric' | 'percent' | 'pf' | 'ratio' | 'seconds' | 'semitones' | 'unverified';

/** One entry in a gen-3 device parameter catalog. */
export interface Param {
  /**
   * Effect family symbol (e.g. `'REVERB'`, `'DELAY'`, `'COMP'`).
   * Sourced from the dispatcher's case → table-of-params mapping.
   */
  family: string;
  /**
   * Parameter ID within the family. Wire-encoded as a 14-bit
   * septet pair in fn=0x01 PARAMETER_SETGET frames. Values >= 65520 are
   * firmware-internal sentinels and NOT wire-addressable — see
   * the III catalog's file-level header for details.
   */
  paramId: number;
  /**
   * Symbol name from the device editor's binary (e.g. `'REVERB_TYPE'`).
   * Stable across firmware releases of the same generation.
   */
  name: string;
  /**
   * Human-readable display label from the AxeEdit III JUCE-BinaryData
   * XML mining — the editor's knob caption (e.g. `'Drive'` for
   * `DISTORT_DRIVE`, `'Reverb Time'` for `REVERB_TIME`). Populated
   * for ~91% of catalog entries; absent for symbols the editor
   * doesn't render (firmware-internal blocks, sentinel paramIds).
   * Useful as LLM prompt context independent of unit/range.
   */
  displayLabel?: string;
  /**
   * Display unit tag. `'unverified'` until hardware confirms
   * the real shape; otherwise inferred from one of three sources
   * (see the III catalog's file-level header for provenance — these
   * are display conventions, not wire encodings).
   */
  unit: Unit;
  /**
   * Display range minimum. Populated for AM4-inferred entries
   * (`// inferred from AM4` trailing comment), absent for
   * `unit: 'unverified'` entries.
   */
  displayMin?: number;
  /** Display range maximum. Same population rule as `displayMin`. */
  displayMax?: number;
  /**
   * Optional non-linear scaling, AM4-inferred. `'log10'` for
   * time / frequency knobs that span multiple decades. Absent
   * for linear knobs or `'unverified'` entries.
   */
  scaling?: 'linear' | 'log10';
}
