/**
 * Axe-Fx II lineage-lookup helpers — Fractal Audio's authored lineage
 * info for amp / drive / reverb / delay models on the Axe-Fx II family.
 *
 * Data lives in `src/fractal/shared/lineage/axefx2-{block}-lineage.json`,
 * generated by `scripts/extract-axe-fx-ii-lineage.ts` from the Fractal
 * wiki's amp/drive/reverb/delay pages re-keyed against the Axe-Fx II
 * enum tables in `src/fractal/axe-fx-ii/params.ts`. Each record carries
 * a `matchVia` field (`direct` / `reverb-swap` / `abbrev-expand` /
 * `prefix` / `unmatched`) that signals match-strategy confidence.
 *
 * Three call shapes mirror `am4_lookup_lineage`:
 *   forward    — { name }                 → exact-or-substring on axefx2Name
 *   reverse    — { real_gear }            → score across basedOn / quotes / prose
 *   structured — { manufacturer, model }  → exact match on basedOn structured fields
 *
 * Helper is exported from a dedicated module so the lookup tool stays
 * thin and so future Hydrasynth lineage support can follow the same
 * shape (one helper per device family).
 */

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

import { formatLoudnessAppendix } from '../../core/fractal-shared/loudness.js';

const require = createRequire(import.meta.url);
// Axe-Fx II lineage JSON lives alongside AM4 lineage data inside the
// fractal-midi package's shared/ subpath. Resolve via the package's
// exports so the path works whether we run from source (tsx) or built dist.
const coreLineageLookup = require.resolve('../../shared/index.js');
const LINEAGE_DIR = path.join(path.dirname(coreLineageLookup), 'lineage');

export const AXE_FX_II_LINEAGE_BLOCKS = ['amp', 'drive', 'reverb', 'delay'] as const;
export type AxeFxIILineageBlock = typeof AXE_FX_II_LINEAGE_BLOCKS[number];

/** Match-strategy confidence (carried through from the extractor). */
export type AxeFxIIMatchVia =
    | 'direct'
    | 'reverb-swap'
    | 'abbrev-expand'
    | 'prefix'
    | 'unmatched';

export interface AxeFxIILineageRecord {
    /** UPPERCASE display name from the Axe-Fx II enum table (always present). */
    axefx2Name: string;
    /** Wire index 0..N within the enum (for cross-referencing setParam encoding). */
    wireIndex: number;
    /** Match-strategy confidence — `direct` is name-exact; others should be spot-checked. */
    matchVia: AxeFxIIMatchVia;
    /** Lineage prose — empty for `unmatched` records. */
    am4Name?: string;
    wikiName?: string;
    description?: string;
    family?: string;
    familyType?: string;
    powerTubes?: string;
    originalCab?: string;
    matchingDynaCab?: string;
    basedOn?: {
        primary: string;
        manufacturer?: string;
        model?: string;
        productName?: string;
        source: string;
    };
    fractalQuotes?: Array<{ text: string; url?: string; attribution?: string }>;
    artistNotes?: unknown[];
    flags: string[];
}

const lineageCache: Partial<Record<AxeFxIILineageBlock, AxeFxIILineageRecord[]>> = {};

export function loadAxeFxIILineage(block: AxeFxIILineageBlock): AxeFxIILineageRecord[] {
    const cached = lineageCache[block];
    if (cached) return cached;
    const file = path.join(LINEAGE_DIR, `axefx2-${block}-lineage.json`);
    if (!fs.existsSync(file)) {
        throw new Error(
            `Axe-Fx II lineage data missing at ${file}. Regenerate via ` +
            `\`npm run extract-axe-fx-ii-lineage\` (the extractor re-keys the ` +
            `AM4 wiki lineage against the Axe-Fx II enum tables).`,
        );
    }
    const parsed = JSON.parse(fs.readFileSync(file, 'utf8')) as { records?: AxeFxIILineageRecord[] };
    const records = parsed.records ?? [];
    lineageCache[block] = records;
    return records;
}

export function scoreAxeFxIIRecord(rec: AxeFxIILineageRecord, query: string): number {
    const q = query.toLowerCase();
    let score = 0;
    if (rec.basedOn?.manufacturer?.toLowerCase() === q) score += 20;
    if (rec.basedOn?.model?.toLowerCase() === q) score += 20;
    if (rec.basedOn?.productName?.toLowerCase().includes(q)) score += 12;
    if (rec.axefx2Name.toLowerCase().includes(q)) score += 10;
    if (rec.am4Name && rec.am4Name.toLowerCase().includes(q)) score += 8;
    if (rec.basedOn?.primary.toLowerCase().includes(q)) score += 8;
    if (rec.wikiName && rec.wikiName.toLowerCase().includes(q)) score += 5;
    if (rec.description && rec.description.toLowerCase().includes(q)) score += 5;
    for (const qt of rec.fractalQuotes ?? []) {
        if (qt.text.toLowerCase().includes(q)) score += 2;
    }
    return score;
}

export function matchesStructuredAxeFxII(
    rec: AxeFxIILineageRecord,
    filter: { manufacturer?: string; model?: string },
): boolean {
    if (!rec.basedOn) return false;
    const ci = (a: string | undefined, b: string | undefined): boolean =>
        !b || (a?.toLowerCase() === b.toLowerCase());
    return (
        ci(rec.basedOn.manufacturer, filter.manufacturer) &&
        ci(rec.basedOn.model, filter.model)
    );
}

export function formatAxeFxIILineageRecord(
    rec: AxeFxIILineageRecord,
    includeQuotes: boolean,
    maxQuotes = 5,
): string {
    const lines: string[] = [`axefx2Name: ${rec.axefx2Name}`, `wireIndex: ${rec.wireIndex}`];
    lines.push(`matchVia: ${rec.matchVia}`);
    if (rec.am4Name && rec.am4Name !== rec.axefx2Name) lines.push(`am4Name: ${rec.am4Name}`);
    if (rec.wikiName && rec.wikiName !== rec.axefx2Name && rec.wikiName !== rec.am4Name) {
        lines.push(`wikiName: ${rec.wikiName}`);
    }
    if (rec.family) lines.push(`family: ${rec.family}`);
    if (rec.familyType) lines.push(`familyType: ${rec.familyType}`);
    if (rec.powerTubes) lines.push(`powerTubes: ${rec.powerTubes}`);
    if (rec.originalCab) lines.push(`originalCab: ${rec.originalCab}`);
    if (rec.matchingDynaCab) lines.push(`matchingDynaCab: ${rec.matchingDynaCab}`);
    if (rec.basedOn) {
        const parts: string[] = [`basedOn: ${rec.basedOn.primary}`];
        if (rec.basedOn.manufacturer) parts.push(`manufacturer=${rec.basedOn.manufacturer}`);
        if (rec.basedOn.model) parts.push(`model=${rec.basedOn.model}`);
        if (rec.basedOn.productName) parts.push(`productName="${rec.basedOn.productName}"`);
        parts.push(`source=${rec.basedOn.source}`);
        lines.push(parts.join(' | '));
    }
    if (rec.description) lines.push(`description: ${rec.description}`);
    if (includeQuotes && rec.fractalQuotes?.length) {
        const shown = rec.fractalQuotes.slice(0, maxQuotes);
        lines.push(`fractalQuotes (${shown.length}/${rec.fractalQuotes.length}):`);
        for (const q of shown) {
            const url = q.url ? ` [${q.url}]` : '';
            lines.push(`  - "${q.text}"${url}`);
        }
    }
    if (rec.flags?.length) lines.push(`flags: ${rec.flags.join('; ')}`);
    // BK-064 part 1 wiring: surface per-amp / per-drive loudness data
    // when the corpus has an entry. Corpus is keyed by AM4 display
    // name; lineage records carry `am4Name` as the cross-device key.
    // Fall back to `axefx2Name` for identical-name records.
    const loudnessAppendix = formatLoudnessAppendix(rec.am4Name ?? rec.axefx2Name);
    if (loudnessAppendix) lines.push(loudnessAppendix);
    return lines.join('\n');
}

export type AxeFxIILineageLookupAsk = {
    block_type: AxeFxIILineageBlock;
    name?: string;
    real_gear?: string;
    manufacturer?: string;
    model?: string;
};

export type AxeFxIILineageLookupHit = {
    axefx2Name: string;
    record: AxeFxIILineageRecord;
    score?: number;
};

export type AxeFxIILineageLookupResult =
    | {
        ask: AxeFxIILineageLookupAsk;
        found: true;
        shape: 'forward' | 'reverse' | 'structured';
        hits: AxeFxIILineageLookupHit[];
        totalScanned: number;
    }
    | {
        ask: AxeFxIILineageLookupAsk;
        found: false;
        shape: 'forward' | 'reverse' | 'structured' | 'invalid';
        reason: string;
        totalScanned: number;
    };

/**
 * Run a single Axe-Fx II lineage lookup. Throws Error only for shape-
 * validation failures (exactly-one-call-shape, real_gear too short);
 * data misses return `{ found: false, reason }` so a batch caller can
 * keep going.
 */
export function runAxeFxIILineageLookup(
    ask: AxeFxIILineageLookupAsk,
): AxeFxIILineageLookupResult {
    const hasStructured = !!(ask.manufacturer || ask.model);
    const shapeCount = [ask.name !== undefined, ask.real_gear !== undefined, hasStructured].filter(Boolean).length;
    if (shapeCount !== 1) {
        throw new Error(
            'lookup_lineage requires exactly one call shape: `name` (forward), `real_gear` (fuzzy reverse), or at least one structured filter (`manufacturer` / `model`).',
        );
    }
    const records = loadAxeFxIILineage(ask.block_type);

    if (hasStructured) {
        const matches = records.filter((r) => matchesStructuredAxeFxII(r, { manufacturer: ask.manufacturer, model: ask.model }));
        if (matches.length === 0) {
            const filter = [
                ask.manufacturer && `manufacturer="${ask.manufacturer}"`,
                ask.model && `model="${ask.model}"`,
            ].filter(Boolean).join(', ');
            return {
                ask,
                found: false,
                shape: 'structured',
                reason: `No ${ask.block_type} records match ${filter}.`,
                totalScanned: records.length,
            };
        }
        return {
            ask,
            found: true,
            shape: 'structured',
            hits: matches.slice(0, 10).map((r) => ({ axefx2Name: r.axefx2Name, record: r })),
            totalScanned: records.length,
        };
    }

    if (ask.name !== undefined) {
        const q = ask.name.toLowerCase().trim();
        const exact = records.find(
            (r) =>
                r.axefx2Name.toLowerCase() === q
                || r.am4Name?.toLowerCase() === q
                || r.wikiName?.toLowerCase() === q,
        );
        const partial = exact ?? records.find(
            (r) =>
                r.axefx2Name.toLowerCase().includes(q)
                || r.am4Name?.toLowerCase().includes(q)
                || r.wikiName?.toLowerCase().includes(q),
        );
        if (!partial) {
            return {
                ask,
                found: false,
                shape: 'forward',
                reason: `No ${ask.block_type} lineage record matches "${ask.name}".`,
                totalScanned: records.length,
            };
        }
        return {
            ask,
            found: true,
            shape: 'forward',
            hits: [{ axefx2Name: partial.axefx2Name, record: partial }],
            totalScanned: records.length,
        };
    }

    // Reverse lookup.
    const query = ask.real_gear!.trim();
    if (query.length < 2) {
        throw new Error('`real_gear` query must be at least 2 characters.');
    }
    const scored = records
        .map((r) => ({ r, score: scoreAxeFxIIRecord(r, query) }))
        .filter((x) => x.score > 0)
        .sort((a, b) => b.score - a.score)
        .slice(0, 10);

    if (scored.length === 0) {
        return {
            ask,
            found: false,
            shape: 'reverse',
            reason: `No ${ask.block_type} records mention "${query}".`,
            totalScanned: records.length,
        };
    }
    return {
        ask,
        found: true,
        shape: 'reverse',
        hits: scored.map(({ r, score }) => ({ axefx2Name: r.axefx2Name, record: r, score })),
        totalScanned: records.length,
    };
}
