/**
 * AM4 agent guidance — migrated from the long device-namespaced tool
 * descriptions in `src/fractal/am4/tools/{write,read,navigation,apply}.ts`.
 *
 * v0.3 removed the device-namespaced tool surface; the LLM no longer sees
 * these guidance blocks through tool descriptions. They surface instead
 * via `describe_device({ port: 'am4' }).agent_guidance` so the agent can
 * load them once per session and refer to them while planning
 * tone-building / preset-applying calls.
 *
 * Topic keys are device-defined — read the corresponding topic to
 * understand the behavioral contract. Keys are stable across releases.
 */

export const AM4_AGENT_GUIDANCE: Readonly<Record<string, string>> = {
  diagnostic_isolation: [
    'When the user reports an unwanted artifact in a tone (boomy low end,',
    'fizzy attack, wash on the tail), isolate via set_bypass: toggle one',
    'block at a time (amp / drive / cab / fx_loop / reverb / delay) and',
    'ask the user to play between toggles, before changing any param',
    'values. The human-in-the-loop is the test signal. Bulk edits across',
    'multiple blocks during diagnosis hide which change mattered;',
    'isolation surfaces the source one round-trip at a time. Batching is',
    'correct for confident builds; isolation is the right tool for',
    'chasing artifacts.',
  ].join(' '),

  read_requires_navigation: [
    'IMPORTANT: AM4 cannot read the contents of an arbitrary stored',
    'preset without first navigating to it. scan_locations reads the',
    'NAMES of stored presets remotely (works without navigation), but',
    'get_param / get_params / get_preset only read the WORKING BUFFER,',
    'which holds whichever preset is currently active on the device.',
    'IMPORTANT: the CURRENT active scene IS readable — call get_preset and',
    'read its active_scene field (it comes from the working-buffer',
    'fingerprint). So "what scene am I on right now?" is answerable; do NOT',
    'refuse it. What is NOT readable is an INACTIVE or STORED scene\'s',
    'contents without navigating. If get_preset returns no/!out-of-range',
    'active_scene, surface that the read failed rather than guessing a',
    'number. To read U1\'s contents (block layout, amp',
    'type, gain, etc.), call switch_preset({location:"U1"}) first; the',
    'device loads U1 into the working buffer, then your reads target',
    'U1. Plan for this latency cost up front: a "copy U1 and modify it"',
    'workflow needs one switch_preset before any read sequence.',
    'Hardware constraint (no read-arbitrary-preset SysEx exists), not a',
    'tool limitation we can remove. There is no wire path for indirect',
    'preset reads, period.',
  ].join(' '),

  volume_language: [
    'When the user says "louder / quieter / more reverb", pick the right knob:',
    '`amp.gain` is INPUT DRIVE (changes character), `amp.master` is amp master',
    '(preserves character), `amp.level` is post-amp dB trim for preset-to-preset',
    'matching. `<fx>.mix` is the wet/dry on each effect. Full per-device cheat',
    'sheet: docs/VOLUME-CONTROL.md.',
  ].join(' '),

  loudness: [
    'LOUDNESS MODEL on the AM4. All values are DISPLAY UNITS (what the front',
    'panel reads), never raw wire integers. The dispatcher converts display to',
    'wire automatically, so "amp.master = 5" means knob position 5 of 10, not',
    'wire integer 5.',
    '',
    'The knobs that move loudness, in roughly the order you should reach for',
    'them:',
    '',
    '  amp.gain         0..10 knob   INPUT drive into the amp model. Changes',
    '                                tone character (more breakup, more',
    '                                compression). NOT a clean volume knob.',
    '                                Use when the user says "more gain / drive',
    '                                / distortion / crunch".',
    '  amp.master       0..10 knob   Amp-internal master. Preserves the gain',
    '                                character but lifts the whole amp. Use',
    '                                when the user says "make the amp louder /',
    '                                quieter" without wanting tone change.',
    '                                Many lineages do NOT expose master (Vox',
    '                                AC30, non-master Marshalls). See the',
    '                                amp_voicing_pitfall topic.',
    '  amp.level        -80..+20 dB  Post-amp clean trim. The right knob for',
    '                                "match this preset to the next one" or',
    '                                "this preset is too quiet". 0 dB is unity;',
    '                                moves of ±2 dB are typical.',
    '  drive.level      0..10 knob   Output of the drive block. After',
    '                                amp.gain, this is the second biggest',
    '                                lever on perceived loudness when a drive',
    '                                is engaged. (Cross-device note: II calls',
    '                                this `drive.volume`. III calls it',
    '                                `drive.level` to match AM4. See',
    '                                cross-device-aliases.ts.)',
    '  drive.mix        0..100 %     Wet/dry of the drive block. 100% is the',
    '                                conventional setting for a pedal in',
    '                                front of an amp.',
    '  reverb.mix       0..100 %     Wet/dry of the reverb. 25-40% is a',
    '                                normal room/plate range; above 50% will',
    '                                mask amp mid-range. "More reverb" maps',
    '                                to mix, NOT reverb.level.',
    '  delay.mix        0..100 %     Wet/dry of the delay. 20-35% for',
    '                                rhythmic Edge-style delays; lower for',
    '                                subtle thickening.',
    '  <fx>.mix         0..100 %     Same shape on chorus / flanger /',
    '                                phaser / rotary / tremolo / compressor.',
    '',
    'CROSS-PARAM INTERACTIONS (audio-engineer rules of thumb):',
    '',
    '  - Raising amp.gain typically increases perceived loudness as well as',
    '    distortion. If the user asks for "more crunch but same volume",',
    '    raise amp.gain by N and drop amp.master by roughly N/2.',
    '  - Engaging a drive block in front of an amp usually adds 3-6 dB of',
    '    perceived loudness even at unity drive.level. If you place a drive',
    '    and the user is comparing it to the bypassed tone, expect to drop',
    '    amp.master or amp.level 2-3 dB to keep stage level constant.',
    '  - Reverb.mix above 50% masks 1-3 kHz mid-range. If the user reports',
    '    "the lead lost its bite after I added reverb", reverb.mix is the',
    '    likely cause. Pull it back to 25-35%.',
    '  - amp.gain and amp.master are not independent: lineages with no master',
    '    knob (AC30 family, Plexi 100W variants, 1959SLP) tie gain directly',
    '    to the power section, so amp.gain is the only volume control for',
    '    that amp on those lineages. Use amp.level for clean trim instead.',
    '',
    'CROSS-DEVICE NAMING. The same conceptual knob has different canonical',
    'names across Fractal devices:',
    '',
    '  AM4 drive.level        ↔  Axe-Fx II drive.volume        ↔  Axe-Fx III drive.level',
    '  AM4 amp.master         ↔  Axe-Fx II amp.master_volume   ↔  Axe-Fx III amp.master',
    '  AM4 amp.gain           ↔  Axe-Fx II amp.input_drive     ↔  Axe-Fx III amp.gain',
    '',
    'The unified surface ships a cross-device alias table',
    '(packages/core/src/protocol-generic/cross-device-aliases.ts) that lets',
    'an agent trained on the II vocabulary type `drive.volume` on AM4 and',
    'have it resolve silently to `drive.level`. Prefer the canonical name',
    'when writing, and quote the canonical name back when summarizing the',
    'change to the user.',
    '',
    'LEVELING — UNITY MATCH (this is Fractal\'s own published philosophy,',
    'confirmed against the Fractal wiki + forum). The DEFAULT is UNITY: balance',
    'every scene (and every preset) so its AVERAGE signal sits on the WHITE',
    'LINE (0 dB) of the Internal Levels Meter on the Main Levels page. That',
    '0 dB line is the sweet spot — strong signal with ample headroom. RED IS',
    'NOT CLIPPING: the meter is calibrated with ~12 dB of headroom at the red',
    'line (OUT knob at max), so brief peaks above the white line are fine.',
    'Match the AVERAGE, not the peaks, then confirm by ear.',
    '',
    'GAIN IS A LOUDNESS CONTROL IN DISGUISE. Distortion raises average power, so',
    'a clean low-gain scene meters FAR BELOW a saturated high-gain scene at the',
    'same level/master. Set amp.gain / amp.master / drive / mix for TONE first,',
    'expect the scenes to diverge in metered loudness, then neutralize the',
    'difference with the leveling tools below. The common mistake (and what the',
    'old guidance wrongly encoded as "clean -3 dB") is making the clean scene',
    'QUIETER — it is already the quietest. A clean scene typically needs a',
    'POSITIVE trim of +6..+12 dB relative to the high-gain scenes as a starting',
    'point (live-verified 2026-06-06: a clean scene needed ~+11..+15 dB of total',
    'trim to meet the gain scenes).',
    '',
    'AM4 LEVELING TOOLS, in order of reach:',
    '  preset.scene_1_level..scene_4_level  ±20 dB  PRIMARY scene-to-scene',
    '                                match. Post-chain, changes no tone, and',
    '                                needs NO channel switch — also the most',
    '                                reliable to write. The device\'s intended',
    '                                scene-balance control (Main Levels page',
    '                                Scene Level knobs). If a clean scene needs',
    '                                more than +20 dB, also raise amp.master or',
    '                                amp.level on its channel.',
    '  preset.level          -80..+20 dB  Whole-preset trim. Match THIS preset',
    '                                against your OTHER presets, not for scene',
    '                                balance.',
    '  amp.level (per channel) -80..+20 dB  Secondary trim, useful on non-master',
    '                                amps (AC30, non-master Marshalls). Needs a',
    '                                channel switch (can drop an ack and need a',
    '                                retry) — prefer scene_N_level.',
    '  amp.out_boost_level   0..+4 dB  + amp.out_boost (ON/OFF): the footswitch',
    '                                Out Boost, written per channel. The clean',
    '                                way to do a ~+3 dB SOLO LIFT without moving',
    '                                the scene\'s base level.',
    '  preset.balance               stereo L/R, NOT loudness. Leave at 0.',
    '  top-panel OUT (Analog Level)  room master, set once per venue, never for',
    '                                scene balance.',
    '',
    'THE AGENT CANNOT READ THE METER OVER MIDI. After any multi-scene build, set',
    'starting trims from the heuristics above, then LABEL THEM UNVERIFIED, point',
    'the player at the Main Levels page (white line = unity), have them play each',
    'scene normally and report where each average sits, and trim from there. The',
    'human meter read is the test signal — the same human-in-the-loop pattern as',
    'bypass isolation.',
    '',
    'BAKE LEVELS INTO THE FIRST APPLY; DO NOT LOOP get_param TO CHECK LOUDNESS.',
    'Compute the starting estimates (per-amp offset + the clean +6..+12 gain',
    'compensation) WHILE planning the build and put them IN the apply_preset',
    'call — per-channel amp.level inside the channel map — so the preset lands',
    'roughly balanced in ONE call. get_param CANNOT verify loudness: it echoes',
    'the value you just wrote, not the meter, so reading levels back in a',
    'get->set->get loop is wasted round-trips (and burns the tool budget)',
    'without telling you anything new. For scene matching, send ONE set_params',
    'of preset.scene_N_level after the build, label it unverified, and STOP —',
    'ask the player for the meter. Apply at most ONE correction per meter',
    'report. Never iterate levels blind against get_param.',
    '',
    'SANCTIONED DEVIATION: a solo scene may sit ~+3 dB above unity (the',
    'documented solo lift); prefer amp.out_boost_level for it. Everything else',
    'defaults to unity. Arrangement-style spreads (clean sits back in the mix)',
    'are the scene_leveling arrangement_* recipes — opt-in only, NOT the default.',
    '',
    'PER-AMP LOUDNESS OFFSETS. Different amp models meter at different loudness',
    'at the same master/level. The per-amp dB offset is surfaced on the enum',
    'table:',
    '  list_params({port:"am4", block:["amp"], name:["type"]}).params[0]',
    '      .enum_value_loudness_offsets_db',
    'a map of amp model label -> dB offset vs the reference amp (Twin Reverb /',
    '"Double Verb Normal" at master=6 = 0 dB). Same field on drive.type for',
    'boost offsets (T808 OD at level=7 = +6 dB reference). Apply it as a starting',
    'correction. If an amp you used has NO entry, treat the offset as UNKNOWN and',
    'SAY SO ("offset unknown, verify by meter") — do NOT silently assume 0 dB',
    'reference, which is how an unbalanced build slips through.',
  ].join('\n'),

  relative_change: [
    'IMPORTANT for words like "more", "less", "a bit", "significantly",',
    '"raise/lower", "increase/decrease", "double/halve": these only have',
    'meaning relative to the current value. Call `get_param` FIRST to read',
    'the starting point, then compute the absolute target and pass that to',
    '`set_param`. Without the read, the agent is guessing the absolute value',
    '(gain at 2.0 → +3 is "significantly"; gain at 8.0 → +1 is',
    '"significantly"). Skip the read only when the user gives an absolute',
    'value ("set the gain to 6", "treble at 4"). Same anchor pattern works',
    'for read-before-tweak summaries: "amp.gain is currently 3.00; I\'ll',
    'change it to 6.50" gives the user a chance to redirect.',
  ].join(' '),

  tempo_time_discipline: [
    'IMPORTANT for delay / chorus / flanger / phaser / tremolo / rotary: each',
    'of these blocks has a `tempo` enum (NONE plus musical divisions',
    '1/64..1/2..1..4). When `tempo` is anything other than NONE, the AM4',
    'LOCKS the block\'s timing param to (song tempo × division) and SILENTLY',
    'IGNORES absolute writes to that timing param. The locked param is',
    '`delay.time` for delay and `rate` for chorus / flanger / phaser /',
    'tremolo / rotary. Read the `tempo` value alongside time/rate before',
    'planning a change so you know which side of the sync to write. When you',
    'DO need to write `time` or `rate` in absolute units, FIRST set the',
    'block\'s `tempo` to "NONE", otherwise the write is silently overridden.',
    'Order: (1) set tempo to "NONE", (2) write time/rate. Going the other',
    'direction (setting tempo to a division) does not require clearing',
    'time/rate first; the AM4 just stops reading it.',
  ].join(' '),

  delay_tempo_default: [
    'For DELAY specifically: tempo-synced repeats are the PROFESSIONAL DEFAULT',
    'for guitarists in modern popular music. When the user asks for a delay',
    'tone (especially "ambient", "obvious", "rhythmic", "Edge / U2 style",',
    '"post-rock", "shoegaze", "worship", "atmospheric"), REACH FOR `delay.tempo`',
    'FIRST and pick a musical division: 1/4 DOT is the iconic Edge sound, 1/4',
    'for clear rhythmic repeats, 1/2 DOT or 1/2 for ambient washes, 1/8 DOT',
    'for rhythmic urgency, 1/8 for tighter syncopation. Fall back to absolute',
    '`delay.time` only when the user explicitly asks for a specific ms count,',
    'calls out free-time / rockabilly / slapback, or is playing without a',
    'tempo reference.',
    'For MODULATION blocks (chorus / flanger / phaser / rotary): free-Hz',
    '`rate` is the typical default; these are textural, not rhythmic, and',
    'tempo sync rarely matches the ask. Tremolo is the exception: rhythmic',
    'chops (1/8 / 1/16 tempo) are common alongside vintage Hz-rate tremolo.',
  ].join(' '),

  channel_scene_model: [
    'IMPORTANT for user requests that mention scenes: Each block',
    '(amp/drive/reverb/delay) holds its parameter values in one of four',
    'channels A/B/C/D. Scenes are selectors: they choose which channel each',
    'block uses (plus per-block bypass state), they don\'t store param values',
    'themselves. Two scenes pointing at the same channel will both reflect',
    'any write to that channel. If the user says "change the amp gain on',
    'scene 2" they usually mean "on whichever channel scene 2 uses for Amp",',
    'pass the `channel` argument to `set_param` to target a specific',
    'A/B/C/D. Without `channel`, the write goes to whatever channel the',
    'block is on now, which may be shared across multiple scenes. Only amp /',
    'drive / reverb / delay have channels; other blocks (chorus, flanger,',
    'phaser, filter, comp, geq, peq, tremolo, rotary, wah, enhancer, gate,',
    'volpan, ingate) ignore the `channel` argument.',
    'apply_preset SHAPE: channel blocks (amp/drive/reverb/delay) take',
    'CHANNEL-NESTED params: `{A: {gain: 6}, D: {gain: 8}}`. Non-channel',
    'blocks take FLAT params: `{rate: 0.8, depth: 35}`. Sending channel-',
    'nested params on a non-channel block (e.g. `chorus.params = {A: {rate:',
    '0.8}}`) is rejected; the block has no channel register to write to.',
    'Pick the shape per slot.',
  ].join(' '),

  enum_name_reporting: [
    'When you write an enum param (amp.type, drive.type, reverb.type,',
    'delay.type, compressor.type, etc.), the response surfaces the FULL',
    'resolved name in parentheses, e.g. `compressor.type = 8 (JFET Studio',
    'Compressor)`. When summarizing the change to the user, use that',
    'resolved name verbatim, not the shorthand you typed in. The relaxed',
    'matcher accepts partial names ("Studio" → "JFET Studio Compressor"),',
    'so the resolved name disambiguates which specific model loaded. Saying',
    '"I set the compressor to Studio" when the response said "JFET Studio',
    'Compressor" mis-describes the result.',
  ].join(' '),

  reverb_naming_convention: [
    'IMPORTANT: reverb types follow a "Category, Subtype" pattern: "Room,',
    'Small" / "Room, Medium" / "Room, Large" / "Hall, Small" / "Hall, Medium"',
    '/ "Plate, Medium" / "Plate, London" / "Spring, Tube" / "Chamber, Deep"',
    '/ "Echo, Plate" / "SFX Pegasus" / "Cloud, Cumulonimbus" etc. Pass the',
    'FULL "Category, Subtype" string. Passing just "Room" or "Plate" matches',
    'multiple entries and is rejected as ambiguous. When the user says',
    '"small room reverb" pick "Room, Small"; "plate reverb" pick "Plate, Medium"',
    '(or call list_params(port, "reverb", "type") for the full list and',
    'pick a specific one). Default sizes when the user is non-specific:',
    'Room/Hall/Plate pick "Medium" subtype; Spring pick "Medium" or "Tube" for',
    'vintage.',
  ].join(' '),

  amp_voicing_pitfall: [
    'CRITICAL: many amp lineages on AM4 model real-circuit amps that',
    'DON\'T have certain knobs. Writing those knobs is silently no-op\'d on',
    'the device; the wire write acks but the value doesn\'t apply.',
    '',
    'Common silent-no-op traps:',
    '  • Vox AC30 lineages (Class-A 30W TB, AC30 TB, AC30 Brilliant, etc.)',
    '    have NO master volume; real AC30s don\'t have a master knob.',
    '    `amp.master` silently drops. Use `amp.level` (post-amp dB) for',
    '    output trim.',
    '  • Non-master Marshalls (Plexi 100W variants, 1959SLP, 1987X): same',
    '    deal. No master; gain knob drives the power amp directly.',
    '  • Tweed / blackface Fenders: many lack `presence`, `depth`, or',
    '    advanced power-section knobs (`negative_feedback`, `bias_x`).',
    '',
    'AGENT BEHAVIOR, minimize the param set:',
    '  1. Write ONLY the knobs the user explicitly asked for. If the user',
    '     says "Vox AC30 with the gain rolled back", set ONLY gain. Do not',
    '     add master / bass / mid / treble / level / presence "to be',
    '     helpful"; those are the user\'s territory.',
    '  2. Before writing multiple amp knobs, call find_compatible_types({',
    '     port, block: "amp", params: ["master", "presence", "depth"...]})',
    '     to confirm the target lineage exposes all of them. Pick a',
    '     lineage from the returned subset.',
    '  3. When the response carries a "Dropped X param" warning, name the',
    '     dropped params and the reason in your user-facing summary. Do',
    '     NOT report success as if the value applied; the device ignored',
    '     it.',
    '',
    'PARAM NAME aliases: AM4 uses `amp.mid` (not `middle`), `amp.master`',
    '(not `master_volume`), `amp.bass`/`treble` (not `low`/`high`).',
    'list_params(port, "amp") returns the canonical names.',
  ].join('\n'),

  reverb_decay_pitfall: [
    'CRITICAL: Hall, Room, Chamber, and Cloud variants on AM4 are FIXED-',
    'DECAY ALGORITHMS. They do NOT expose the `time` knob. Writing',
    '`reverb.time = N` on a Hall/Room/Chamber/Cloud type silently no-ops on',
    'the device; the wire write acks but the actual decay doesn\'t change.',
    '',
    'TYPES THAT EXPOSE `reverb.time` (use these for "long decay", "long',
    'tail", "big reverb", "ambient reverb", "cathedral", "shimmer", any',
    'time-shapeable reverb tone): **Plate** (Plate, Small/Medium/Large/',
    'London/Sun/Vocal/Gold), **Spring** (Spring, Small/Medium/Large/Deluxe/',
    'Tube/Studio/Vibrato-King/British/Lush), **Echo** (Echo, Plate/Hall/',
    'Room/Fields of Pyrite/Pitch Plate), **SFX** (Sagittarius / Gemini /',
    'Capricorn / Aquarius / Andromeda / Pegasus / Centaurus / Ursa Major /',
    'Pleiades). 31 of the 79 reverb types expose `time`.',
    '',
    'PITFALL, common user phrasings that MUST map to a time-exposing type:',
    '  • "long hall reverb" picks "Plate, Large" or "Echo, Hall" (NOT "Hall, *")',
    '  • "cathedral reverb" picks "Plate, London" or "SFX Andromeda"',
    '  • "ambient reverb" picks "Plate, London" or "Echo, Fields of Pyrite"',
    '  • "shimmer reverb" picks "Echo, Pitch Plate"',
    '  • "spring reverb" picks "Spring, Tube" or "Spring, Vibrato-King"',
    '',
    'When in doubt, call find_compatible_types({port, block:"reverb",',
    'params:["time"]}); it returns the exact subset of reverb types that',
    'expose `time`. Pick from that list. The same applies to any param the',
    'user wants to control: query find_compatible_types BEFORE picking a',
    '`type` enum.',
  ].join('\n'),

  param_name_aliases: [
    'Common synonyms resolve silently to the canonical registered name:',
    '`reverb.decay` / `reverb.length` → `reverb.time`; `delay.length` →',
    '`delay.time`; `delay.repeats` → `delay.feedback`;',
    '`<modulation_block>.speed` → `<...>.rate` (chorus, flanger, phaser,',
    'tremolo, rotary). The response shows the canonical name in the ack',
    '("delay.feedback = 50"); use that name in your summary, not the alias',
    'you passed in.',
  ].join(' '),

  ack_caveat: [
    'IMPORTANT: the AM4 wire-acks every write whether or not the target',
    'block is placed in the active preset, or whether the write landed on',
    'a channel the current scene is using. The response includes the raw',
    'ack bytes for diagnostics, but the only trustworthy signal that a',
    'change took effect is the user confirming via the AM4\'s own display.',
    'If the user expects an audible change and reports none, the likely',
    'cause is (a) the target block isn\'t placed in the active preset, or',
    '(b) the write landed on a channel the active scene isn\'t using.',
  ].join(' '),

  lineage_batching: [
    'lookup_lineage `name` is ALWAYS an array. Multi-amp scene builds',
    '(clean reference + drive amp, or progressive A/B/C/D amp channels)',
    'should pass every name in ONE call:',
    '  lookup_lineage({port:"am4", block_type:"amp",',
    '                  name:["USA MK IIC+","Deluxe Verb Normal"]})',
    'Returns {entries:[...]} with loudness per entry. Two sequential',
    'calls cost you a turn each; one batched call costs one turn.',
  ].join(' '),

  save_intent_required: [
    'SAVE INTENT REQUIRED: call save / persist tools (apply_preset with',
    'target_location, save_preset, switch_preset-with-save) ONLY when the',
    'user has explicitly asked to save, persist, store, or keep the preset',
    '(e.g. "save this", "put it on Z4", "keep this one"). Do NOT call save',
    'as an automatic follow-up to apply_preset; apply is reversible (the',
    'user can switch presets to discard), save is not. A request like "build',
    'a preset for X" is a try-it-out ask; without an explicit save phrase,',
    'apply and let the user decide whether to save. When in doubt, use',
    'apply_preset (with its optional name field) without target_location and',
    'ask the user whether to persist.',
  ].join(' '),

  write_safety_locations: [
    'Any A1..Z4 preset location is accepted for save. The server gates',
    'overwrites: if the target is OCCUPIED and is NOT the location currently',
    'loaded in the working buffer, save_preset refuses and returns the name of',
    'the preset it would replace. Confirm with the user, then retry with',
    'confirm_overwrite:true. Saving over the active (currently-edited) location,',
    'or to an empty location, proceeds without a prompt. There is NO universal',
    'scratch location on the AM4: do not treat any bank as safe-to-clobber;',
    'every occupied non-active target is gated equally.',
    '',
    'BUILD AT DESTINATION vs STASH: if the user names where the preset should',
    'live ("build a lead tone and put it on B2"), audition with apply_preset',
    'first, then save_preset to B2 on an explicit save phrase. Do not "stash"',
    'to an arbitrary location and move it later; save to the named destination.',
    '',
    'LOCATION-CODE DISAMBIGUATION: codes are <bank-letter><2-digit-slot>:',
    '"P1" means P01 (bank P, slot 1), NOT preset #1. Slots are 1..4 per bank.',
    'When the user gives an informal reference ("slot 3", "the second one",',
    '"preset 12"), confirm the exact A01..Z04 code before saving; an',
    'off-by-one here overwrites the wrong preset.',
    '',
    'CONCURRENT-EDITOR HAZARD: if AM4-Edit (or any editor) is open on the same',
    'unit, it can write the working buffer out from under you between your read',
    'and your save, and its on-screen state can be stale relative to the device.',
    'When a save result looks wrong, trust the AM4 front panel and the',
    'save_preset receipt (saved_snapshot), not the editor window.',
  ].join('\n'),

  save_receipt: [
    'SAVE RECEIPT: save_preset returns saved_snapshot read back from the device:',
    'block_chain (the 4 slots), amp_model + drive_model (the model names that',
    'distinguish one preset from another), and preset_name. After saving, tell',
    'the user what actually landed using these values, e.g. "Saved to B2: amp',
    'Brit 800 → drive T808 OD → reverb → delay, named \'Lead Tone\'." This is',
    'the trustworthy confirmation of a save: it is a fresh device read-back,',
    'not an echo of what you sent. If a field is absent, the read-back could',
    'not confirm it (best-effort); say so rather than assuming it landed.',
    '',
    'BATCH CONFIRM-ONCE: when saving several presets in one informed approval',
    '("yes, write all four"), one confirm_overwrite:true per save satisfies the',
    'gate; you do not need to re-prompt the user per location once they have',
    'approved the range.',
  ].join('\n'),

  rename_persistence: [
    'Rename writes target the working buffer only. The new name does NOT',
    'persist across preset loads on its own; pair the rename with a save',
    '(apply_preset with target_location, or save_preset) to persist.',
    'Rename alone is lost when a different preset is loaded; rename + save',
    'persists correctly (hardware-verified 2026-04-19).',
  ].join(' '),

  apply_preset_fresh_vs_tweak: [
    'TWEAK vs FRESH: `apply_preset` REPLACES the working-buffer block layout.',
    'If the user says "tweak my current tone" or "just adjust the reverb",',
    'do NOT call apply_preset; call `set_param` or `set_block` for the',
    'targeted change. apply_preset is for fresh designs ("build me a clean',
    'tone", "design a Mesa rectifier preset"). FRESH-BUILD CLEARING: unlisted',
    'slots get block_type="none" and unlisted scenes are reset to defaults',
    'on every call.',
  ].join(' '),

  state_anchoring: [
    'STATE ANCHORING (read-before-write). When the user references current',
    'state ("make it warmer", "less of that", "match my Sunday Morning tone"),',
    'call get_preset({port:"am4"}) FIRST to snapshot the active working',
    'buffer in one tool call. Latency is ~450 ms for a 4-block preset',
    '(chunk reads). Summarise what is placed before proposing changes.',
    '',
    'RESPONSE SHAPE. The snapshot describes the ACTIVE SCENE only.',
    'Each slot carries: block_type, id, bypassed (boolean), and params.',
    'Channel-bearing blocks (amp, drive, reverb, delay) carry params under',
    'params_by_channel:{A:{...},B:{...},...} when include_channel_state is on;',
    'non-channel blocks (compressor, chorus, filter, etc.) use flat params.',
    'active_scene (1..4) is included. Scenes 2..4 are NOT included;',
    'routing is NOT included (AM4 is a fixed linear chain).',
    '',
    'READ-MUTATE-WRITE PATTERN. To change a few knobs based on the snapshot,',
    'use set_param or set_params for the targeted writes. Do NOT feed the',
    'whole get_preset response back into apply_preset: apply_preset has',
    'FRESH-BUILD CLEARING semantics (unlisted slots clear to none, unlisted',
    'scenes reset to defaults). The snapshot is for INSPECTION and TARGETED',
    'EDITS, not for cloning back wholesale.',
    '',
    'WHEN NOT TO USE get_preset. Targeted single-param questions ("what is',
    'the gain right now?") run faster with get_param (~50 ms). For 2 to 5',
    'specific knobs, use get_params. Use get_preset when you need the whole',
    'layout, not when you already know which knobs you care about.',
  ].join(' '),

  recipe_usage: [
    'RECIPE PICKUP: when the user names a recognizable tone family',
    '("U2 Edge dotted-eighth", "Texas blues crunch", "Master of Puppets',
    'thrash"), scan describe_device("am4").recipes[] for a block_stack',
    'entry whose description matches. If you find one, you MUST apply via',
    'apply_preset({port: "am4", recipe_id: "<id>"}) , NOT by pasting slots',
    'manually. The slim summary deliberately omits the recipe\'s knob',
    'values; pasting manually means improvising those values and hitting',
    'enum / range validation errors. Use the `overrides` arg for targeted',
    'knob tweaks (e.g. raise the amp gain). Recipes are hand-curated from',
    'documented player rigs , a better starting point than improvised',
    'knobs.',
    'The response\'s `applied_spec` field echoes the RESOLVED INPUT (recipe +',
    'overrides), NOT a device readback. It confirms what was sent, not what',
    'landed. For post-write verification, call get_preset.',
    'Single-block recipes (auto_wah on the FILTER block, pitch on PITCH,',
    'wah on WAH, scene_leveling on VOLPAN.volume) ship inline params in',
    'describe_device.recipes[] and apply via set_block + set_params ,',
    'recipe_id is block_stack-only.',
    'AM4 has a 4-slot linear chain. Block_stack recipes that need 5+',
    'slots (djent_gated_5150 etc) are II-only and won\'t appear in your',
    'recipes[] list.',
  ].join(' '),

  channel_led_color: [
    'AMP CHANNEL LED COLOR: each of the four amp channels (A/B/C/D) has',
    'a custom footswitch LED color set via the Amp Type page.',
    'Params: amp.channel_a_color / amp.channel_b_color / amp.channel_c_color',
    '/ amp.channel_d_color. Pass the color name as a string:',
    '  set_param({port:"am4", block:"amp", name:"channel_a_color", value:"Blue"})',
    'Valid colors (in order): Red, Orange, Yellow, Green, Cyan, Blue, Purple.',
    'Hardware-confirmed 2026-06-05 via front-panel scroll on the Amp Type page.',
    'These are PATCH-family params stored per-preset — persist after save_preset.',
    'Writing to amp.channel_*_color is safe even when amp is not in slot 1.',
    'You can also set colors INSIDE apply_preset without a separate call: add a',
    '`color` key to the amp slot\'s per-channel map, e.g.',
    '  channels:{A:{type:"Shiver Clean",gain:3,color:"Purple"},B:{...,color:"Green"}}',
    'The executor routes channel A\'s `color` to amp.channel_a_color, B to',
    'channel_b_color, etc. Prefer this over a trailing set_params when building a',
    'whole preset — it keeps the build to one tool call.',
  ].join(' '),
};
