/**
 * Regenerates src/version.ts from package.json before tsc runs, so the
 * exported VERSION constant never drifts from the published version.
 *
 * This replaced the old runtime `readFileSync(package.json)` in
 * src/index.ts — reading the filesystem at module load made the root
 * entry point Node-only, and the package has to be importable from
 * browser bundles (Axis Browser Direct).
 */
import { readFileSync, writeFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync('package.json', 'utf8')) as { version: string };
const out = `// AUTO-GENERATED by scripts/gen-version.ts from package.json — do not edit by hand.
// Regenerated on every \`npm run build\`; checked in so source imports work without a build step.
export const VERSION: string = '${pkg.version}';
`;
writeFileSync('src/version.ts', out);
console.log(`gen-version: src/version.ts = ${pkg.version}`);
