// GENERATED by scripts/generate-gen1-catalog.ts — DO NOT EDIT BY HAND.
// Axe-Fx Standard/Ultra (gen-1) block roster.
//
// Each block groups its instances (Amp 1 / Amp 2 share params, differ by blockId).
// blockId is the nibble-split 0b0b wire field (e.g. Amp 1 = 106).

import type { AxeFxGen1Block } from './types.js';

export const AXE_FX_GEN1_BLOCKS: readonly AxeFxGen1Block[] = Object.freeze([
  { slug: "compressor", docName: "Compressor", instances: [{ name: "Compressor 1", blockId: 100 }, { name: "Compressor 2", blockId: 101 }] },
  { slug: "graphic_eq", docName: "GraphicEQ", instances: [{ name: "GraphicEQ 1", blockId: 102 }, { name: "GraphicEQ 2", blockId: 103 }, { name: "GraphicEQ 3", blockId: 160 }, { name: "GraphicEQ 4", blockId: 161 }] },
  { slug: "parametric_eq", docName: "ParametricEQ", instances: [{ name: "Parametric EQ 1", blockId: 104 }, { name: "Parametric EQ 2", blockId: 105 }, { name: "Parametric EQ 3", blockId: 162 }, { name: "Parametric EQ 4", blockId: 163 }] },
  { slug: "amp", docName: "Amp", instances: [{ name: "Amp 1", blockId: 106 }, { name: "Amp 2", blockId: 107 }] },
  { slug: "cab", docName: "Cab", instances: [{ name: "Cabinet 1", blockId: 108 }, { name: "Cabinet 2", blockId: 109 }] },
  { slug: "reverb", docName: "Reverb", instances: [{ name: "Reverb 1", blockId: 110 }, { name: "Reverb 2", blockId: 111 }] },
  { slug: "delay", docName: "Delay", instances: [{ name: "Delay 1", blockId: 112 }, { name: "Delay 2", blockId: 113 }] },
  { slug: "multi_delay", docName: "MultiDelay", instances: [{ name: "Multidelay 1", blockId: 114 }, { name: "Multidelay 2", blockId: 115 }] },
  { slug: "chorus", docName: "Chorus", instances: [{ name: "Chorus 1", blockId: 116 }, { name: "Chorus 2", blockId: 117 }] },
  { slug: "flanger", docName: "Flanger", instances: [{ name: "Flanger 1", blockId: 118 }, { name: "Flanger 2", blockId: 119 }] },
  { slug: "rotary", docName: "Rotary", instances: [{ name: "Rotary 1", blockId: 120 }, { name: "Rotary 2", blockId: 121 }] },
  { slug: "phaser", docName: "Phaser", instances: [{ name: "Phaser 1", blockId: 122 }, { name: "Phaser 2", blockId: 123 }] },
  { slug: "wah", docName: "Wah", instances: [{ name: "Wahwah 1", blockId: 124 }, { name: "Wahwah 2", blockId: 125 }] },
  { slug: "formant", docName: "Formant", instances: [{ name: "Formant", blockId: 126 }] },
  { slug: "vol_pan", docName: "VolPan", instances: [{ name: "Vol/Pan 1", blockId: 127 }, { name: "Vol/Pan 2", blockId: 166 }, { name: "Vol/Pan 3", blockId: 167 }, { name: "Vol/Pan 4", blockId: 168 }] },
  { slug: "pan_trem", docName: "PanTrem", instances: [{ name: "Panner/Tremolo 1", blockId: 128 }, { name: "Panner/Tremolo 2", blockId: 129 }] },
  { slug: "pitch", docName: "Pitch", instances: [{ name: "Pitch 1", blockId: 130 }, { name: "Pitch 2", blockId: 153 }] },
  { slug: "filter", docName: "Filter", instances: [{ name: "Filter 1", blockId: 131 }, { name: "Filter 2", blockId: 132 }, { name: "Filter 3", blockId: 164 }, { name: "Filter 4", blockId: 165 }] },
  { slug: "drive", docName: "Drive", instances: [{ name: "Drive 1", blockId: 133 }, { name: "Drive 2", blockId: 134 }] },
  { slug: "enhancer", docName: "Enhancer", instances: [{ name: "Enhancer", blockId: 135 }] },
  { slug: "effects_loop", docName: "EffectsLoop", instances: [{ name: "Effects Loop", blockId: 136 }] },
  { slug: "mixer", docName: "Mixer", instances: [{ name: "Mixer 1", blockId: 137 }, { name: "Mixer 2", blockId: 138 }] },
  { slug: "noise_gate", docName: "NoiseGate", instances: [{ name: "NoiseGate", blockId: 139 }] },
  { slug: "output", docName: "Output", instances: [{ name: "Output", blockId: 140 }] },
  { slug: "controllers", docName: "Controllers", instances: [{ name: "Controllers", blockId: 141 }] },
  { slug: "feedbackreturn", docName: "FeedbackReturn", instances: [{ name: "Feedback Return", blockId: 143 }] },
  { slug: "synth", docName: "Synth", instances: [{ name: "Synth 1", blockId: 144 }, { name: "Synth 2", blockId: 145 }] },
  { slug: "vocoder", docName: "Vocoder", instances: [{ name: "Vocoder", blockId: 146 }] },
  { slug: "mega_tap", docName: "MegaTap", instances: [{ name: "Megatap Delay", blockId: 147 }] },
  { slug: "crossover", docName: "Crossover", instances: [{ name: "Crossover 1", blockId: 148 }, { name: "Crossover 2", blockId: 149 }] },
  { slug: "gate_expander", docName: "GateExpander", instances: [{ name: "Gate/Expander 1", blockId: 150 }, { name: "Gate/Expander 2", blockId: 151 }] },
  { slug: "ring_mod", docName: "RingMod", instances: [{ name: "RingMod", blockId: 152 }] },
  { slug: "multiband_comp", docName: "MultibandComp", instances: [{ name: "Multiband Comp 1", blockId: 154 }, { name: "Multiband Comp 2", blockId: 155 }] },
  { slug: "quad_chorus", docName: "QuadChorus", instances: [{ name: "Quad Chorus 1", blockId: 156 }, { name: "Quad Chorus 2", blockId: 157 }] },
  { slug: "resonator", docName: "Resonator", instances: [{ name: "Resonator 1", blockId: 158 }, { name: "Resonator 2", blockId: 159 }] },
]);

export const BLOCK_BY_SLUG: Readonly<Record<string, AxeFxGen1Block>> = Object.freeze(
  Object.fromEntries(AXE_FX_GEN1_BLOCKS.map((b) => [b.slug, b])),
);

/** Resolve a block slug + 1-based instance to its wire blockId. */
export function blockIdFor(slug: string, instance = 1): number | undefined {
  const b = BLOCK_BY_SLUG[slug];
  return b?.instances[instance - 1]?.blockId;
}
