// Axe-Fx III discrete-ordinal classification overlay (param firmware symbol ->
// maxOrdinal). Ported from upstream fractal-midi 0.6.1
// src/gen3/axe-fx-iii/roundtripDiscrete.generated.ts; CLASSIFICATION ONLY, applied
// as an overlay over our NEWER ranges/rosters (never overwriting our range values).
// NOT a *.generated.ts file: we have no generator for it here, so it is a committed,
// hand-maintained source table. Re-port from upstream if that oracle is regenerated.
//
// Upstream provenance: derived from the device's OWN full hardware roundtrip sweep
// (chihotta-roundtrip-2026-06-18, Axe-Fx III, modelByte 0x10). A param is
// roundtrip-DISCRETE iff across its SET->READ sweep every gotWire is a non-negative
// integer, monotonic non-decreasing in sentWire, and at the max sentWire (65534)
// gotWire <= 1024 AND < sentWire (clearly quantized to a small ordinal, not
// pass-through) AND max gotWire >= 1. maxOrdinal = gotWire at the max sentWire.
//
// These params are routed DISCRETE (float32(ordinal), sub 09 00) instead of
// CONTINUOUS — the wire builder is unchanged; only the catalog kind-classification
// differs, so the gen-3 byte-identity anchor stays intact.
/* eslint-disable */

export const III_ROUNDTRIP_DISCRETE: Readonly<Record<string, number>> = {
  "CABINET_TYPE1": 188,
  "CABINET_TYPE2": 188,
  "CABINET_ZOOM": 1,
  "CHORUS_VOICES": 4,
  "DELAY_BITREDUCE": 24,
  "DELAY_BYPASSMODE": 4,
  "DELAY_GLOBALMIX": 1,
  "DELAY_HOLD": 2,
  "DELAY_HPF_ORDER": 4,
  "DELAY_LFO1TARGET": 2,
  "DELAY_LFO1TEMPO": 78,
  "DELAY_LFO1TYPE": 9,
  "DELAY_LFO2TARGET": 2,
  "DELAY_LFO2TYPE": 9,
  "DELAY_LFO4TARGET": 3,
  "DELAY_LFO4TEMPO": 78,
  "DELAY_LFO4TYPE": 9,
  "DELAY_LPF_ORDER": 4,
  "DELAY_MAXDEPTH": 1,
  "DELAY_MODE": 1,
  "DELAY_MODEL": 28,
  "DELAY_PHASEREV": 3,
  "DELAY_RUN": 1,
  "DELAY_SVFTYPE": 3,
  "DELAY_TEMPO": 78,
  "DELAY_TYPE": 7,
  "DISTORT_BIASTYPE": 2,
  "DISTORT_BOOSTTYPE": 14,
  "DISTORT_BRIGHT": 1,
  "DISTORT_BYPASSMODE": 1,
  "DISTORT_CLIPTYPE2": 12,
  "DISTORT_COMPTYPE": 2,
  "DISTORT_DRIVETYPE": 7,
  "DISTORT_EQONOFF": 1,
  "DISTORT_FAT": 1,
  "DISTORT_FBTYPE": 68,
  "DISTORT_INPUTSELECT": 2,
  "DISTORT_MVPOSITION": 2,
  "DISTORT_OUTPUTTYPE": 1,
  "DISTORT_PLATEDIODE": 1,
  "DISTORT_PRECOMPTYPE": 1,
  "DISTORT_PRESAG": 1,
  "DISTORT_PRESSHIFT": 1,
  "DISTORT_PRETUBETYPE": 8,
  "DISTORT_SATSWITCH": 2,
  "DISTORT_SCENEIGNORE": 1,
  "DISTORT_SPKRBREAKUP": 2,
  "DISTORT_SPKRMODEL": 92,
  "DISTORT_SUPPLYTYPE": 1,
  "DISTORT_TONELOC": 4,
  "DISTORT_TONETYPE": 137,
  "DISTORT_TUBETYPE": 25,
  "FILTER_APORDER": 12,
  "FUZZ_BITREDUCE": 24,
  "FUZZ_NDQTY": 4,
  "FUZZ_PDQTY": 4,
  "MEGATAP_FDBKTAP": 128,
  "MEGATAP_NUMTAPS": 128,
  "MOD_ENDPT": 78,
  "PHASER_FBTAP": 11,
  "PITCH_CUSTOMNOTES": 8,
  "PITCH_CUSTOMSCALE1": 31,
  "PITCH_CUSTOMSCALE2": 31,
  "PITCH_NOTE2": 5,
  "PITCH_NOTE3": 6,
  "PITCH_NOTE4": 7,
  "PITCH_NOTE5": 8,
  "PITCH_NOTE6": 9,
  "PITCH_NOTE7": 10,
  "PITCH_NOTE8": 11,
  "PITCH_NUMREPEATS": 31,
  "PITCH_NUMSTEPS": 16,
  "PLEX_NUMDLINES": 4,
  "PLEX_SHIMMERINTENS": 10,
  "REVERB_BASETYPE": 8,
  "REVERB_BYPASSMODE": 4,
  "REVERB_DENSITY": 8,
  "REVERB_GLOBALMIX": 1,
  "REVERB_HIGHSLOPE": 1,
  "REVERB_HOLD": 2,
  "REVERB_LOWSLOPE": 1,
  "REVERB_NUMSPRINGS": 6,
  "REVERB_PITCHDIR": 3,
  "REVERB_PITCHPOS": 2,
  "REVERB_PREDLYTAP": 1,
  "REVERB_QUALITY": 3,
  "REVERB_SCENEIGNORE": 1,
  "REVERB_SPRINGTYPE": 1,
  "REVERB_TONETYPE": 3,
  "REVERB_TYPE": 78,
  "TENTAP_DECAYSTYLE": 1,
  "TENTAP_NUMTAPS": 10,
};
