// AUTO-GENERATED by scripts/gen-version.ts from package.json — do not edit by hand.
// Regenerated on every `npm run build`; checked in so source imports work without a build step.
export const VERSION: string = '0.3.23';
