/**
 * Generated by scripts/_research/gen-am4-cache-oracle-params.ts -- do not hand-edit.
 * NOT WIRED into KNOWN_PARAMS. Integration is one spread + review:
 *   export const KNOWN_PARAMS = { ...CACHE_PARAMS, ...AMP_GHOST_PARAMS, ...SYSTEM_PARAM_UPDATES, ... }
 *
 * EVIDENCE GRADE: cache-oracle, STRONG format basis.
 *   Source: effectDefinitions_15_2p0.cache, AM4-Edit's metadata cache synced
 *   from a REAL AM4 (fw 2.0) on this machine, walked with the solved cache
 *   grammar (zero-resync, exact section record counts; hardware anchors pass;
 *   the II cache cross-validates 259/259 amp ordinals against the shipped
 *   hardware-verified II catalog). See docs/_private/CACHE-FORMAT-SOLVED-2026-06-09.md.
 *   Record semantics: f32 fields are (min, max, scale, step); display = field x scale.
 *
 * Per the shipping bar this is DONE-pending-confirmation, not "not done":
 * ranges/labels are device-true cache data, hardware-UNCONFIRMED end-to-end.
 * Honesty labels carried per entry:
 *   - Tier-2 type-code enums (HW-129): labels are AM4-native, but the params
 *     are amp-model-internal; recommend read-only exposure.
 *   - CC pick lists: 1-based mapping inferred from the cache min=1/max=count
 *     signature; index base unconfirmed on hardware.
 *   - tc unit-family 7 (tuner offsets): "cents" display suffix is an
 *     inference, the unit family byte is unmapped.
 *   - Taper: scaling 'log10' only for hardware-confirmed typecodes
 *     {0x40,0x44,0x48,0x50}; 0x42/0x43/0x45 are taper-OPEN (predicted log10
 *     by the 0x40-and-not-0x20 rule, kept linear until confirmed).
 *
 * Cross-checks against the shipped catalog (contradictions are NOT resolved
 * here; shipped values unchanged) are documented in
 * docs/_private/AM4-CACHE-ORACLE-EXPANSION-2026-06-09.md.
 */
import type { Param } from './params.js';

/** CC pick lists: 'CC #1'..'CC #127' [+ 'NONE' [+ 'PEDAL 1','PEDAL 2']], 1-based.
 * Pattern byte-verified against every CC-style cache record by the generator. */
function ccLabels(n: 127 | 128 | 130): Record<number, string> {
  const out: Record<number, string> = {};
  for (let i = 1; i <= Math.min(n, 127); i++) out[i] = `CC #${i}`;
  if (n >= 128) out[128] = 'NONE';
  if (n >= 130) { out[129] = 'PEDAL 1'; out[130] = 'PEDAL 2'; }
  return out;
}

/**
 * HW-129 amp GHOSTs (DISTORT family @ pidLow 0x3a) that are device-real
 * (hardware ACK, 2026-05-31 probe) and still unregistered. Ranges/labels from
 * the cache oracle. Excluded: DISTORT_VERSION (id 89, Tier-3 version stamp,
 * degenerate cache range).
 */
export const AMP_GHOST_PARAMS = {
  // DISTORT_XFLEAKAGE -- cache: section 10 id 19, tc=0x00, display [0..1] step 0 (scale 1)
  // HW-129 Tier-1: continuous no-UI advanced register (device ACKs; no front-panel display).
  'amp.xfleakage': {
    block: 'amp', name: 'xfleakage',
    pidLow: 0x003a, pidHigh: 0x0013,
    unit: 'count', displayMin: 0, displayMax: 1,
  },
  // DISTORT_OFFSET1 -- cache: section 10 id 27, tc=0x30, display [-1..1] step 0.002 (scale 1)
  // HW-129 Tier-1: continuous no-UI advanced register (device ACKs; no front-panel display).
  'amp.offset1': {
    block: 'amp', name: 'offset1',
    pidLow: 0x003a, pidHigh: 0x001b,
    unit: 'count', displayMin: -1, displayMax: 1,
  },
  // DISTORT_CLIPTYPE2 -- cache: section 10 id 28, tc=0x10, enum n=13
  // HW-129 Tier-2: amp-model-internal type code. Labels are AM4-native (cache oracle),
  // but arbitrary writes desync the amp model; recommend READ-ONLY exposure.
  'amp.cliptype2': {
    block: 'amp', name: 'cliptype2',
    pidLow: 0x003a, pidHigh: 0x001c,
    unit: 'enum', displayMin: 0, displayMax: 12,
    enumValues: {
      0: 'SOFT', 1: 'HARD', 2: 'SQUARE', 3: 'CUBIC', 4: 'ABS', 5: 'TUBE', 6: 'QUARTIC', 
      7: 'PUSH-PULL', 8: '3/2 HARD', 9: '3/2 SOFT', 10: 'TRIODE', 11: 'TRIODE+SAT', 
      12: 'TRIODE+SAT1',
    },
  },
  // DISTORT_DRIVETYPE -- cache: section 10 id 37, tc=0x10, enum n=8
  // HW-129 Tier-2: amp-model-internal type code. Labels are AM4-native (cache oracle),
  // but arbitrary writes desync the amp model; recommend READ-ONLY exposure.
  'amp.drivetype': {
    block: 'amp', name: 'drivetype',
    pidLow: 0x003a, pidHigh: 0x0025,
    unit: 'enum', displayMin: 0, displayMax: 7,
    enumValues: {
      0: 'NORMAL', 1: 'DUAL', 2: 'JUMPED HIWATT', 3: 'JUMPED BASSMAN', 4: 'JUMPED TWEED', 
      5: 'TWEED', 6: 'GANGED', 7: 'JUMPED PLEXI',
    },
  },
  // DISTORT_WSHPF -- cache: section 10 id 39, tc=0x42, display [2..2000] step 0 (scale 1)
  // HW-129 Tier-1: continuous no-UI advanced register (device ACKs; no front-panel display).
  // taper OPEN: tc=0x42 predicts log10 under the 0x40-and-not-0x20 rule (unconfirmed); linear until verified
  'amp.wshpf': {
    block: 'amp', name: 'wshpf',
    pidLow: 0x003a, pidHigh: 0x0027,
    unit: 'hz', displayMin: 2, displayMax: 2000,
  },
  // DISTORT_TONETYPE -- cache: section 10 id 41, tc=0x10, enum n=138
  // HW-129 Tier-2: amp-model-internal type code. Labels are AM4-native (cache oracle),
  // but arbitrary writes desync the amp model; recommend READ-ONLY exposure.
  'amp.tonetype': {
    block: 'amp', name: 'tonetype',
    pidLow: 0x003a, pidHigh: 0x0029,
    unit: 'enum', displayMin: 0, displayMax: 137,
    enumValues: {
      0: 'ACTIVE', 1: 'DEFAULT', 2: 'BROWNFACE', 3: 'BLACKFACE', 4: 'BASSGUY', 5: 'TOP BOOST', 
      6: 'PLEXI', 7: 'BOUTIQUE', 8: 'HI POWER', 9: 'USA NORMAL', 10: 'USA FAT', 11: 'RECTO1 ORG', 
      12: 'RECTO1 RED', 13: 'SKYLINE', 14: 'GERMAN', 15: 'JR BLUES', 16: 'WRECKER 1', 
      17: 'NEUTRAL', 18: 'CA3+SE', 19: 'FREYER D60', 20: 'MR Z 38 SR', 21: 'EURO UBER', 
      22: 'PVH 6160', 23: 'SOLO 100', 24: 'CORNCOB', 25: 'XTC', 26: 'CAROLANN', 27: 'CITRUS', 
      28: 'BRIT JM45', 29: 'USA RHY', 30: 'RECTO2 ORG', 31: 'RECTO2 RED VNTG', 32: 'SHIVER CLN', 
      33: 'CAMERON', 34: 'BRIT JVM 0D1', 35: 'BRIT JVM 0D2', 36: '5153 GREEN', 37: '5153 BLUE', 
      38: '5153 RED', 39: 'BRIT SUPER', 40: 'DIV13 CJ', 41: 'BADGER 18', 42: 'ATOMICA', 
      43: 'SPAWN ROD', 44: 'BADGER 30', 45: 'BRIT SILVER', 46: 'SUPER VERB', 47: 'HOT KITTY', 
      48: 'VIBRATO-KING', 49: 'GIBTONE SCOUT', 50: 'CA3+SE CLEAN', 51: 'BF FIXED MID', 
      52: 'GERMAN V4', 53: 'VIBRATO-LUX', 54: 'DIRTY SHIRLEY', 55: 'PLEXI 100W', 
      56: 'RUBY ROCKET BRT', 57: 'CONCOURSE', 58: 'TRIPTIK LD', 59: 'TRIPTIK CLN', 60: 'JAZZ 120', 
      61: 'BOGFISH', 62: 'WRECKER 2', 63: 'SKYLINE DEEP', 64: 'USA SUB BLUES', 
      65: 'WRECKER LVRPOOL', 66: 'CITRUS A30 CLN', 67: 'CITRUS A30 DRT', 68: 'CAR ROAMER', 
      69: 'USA BASS', 70: 'CITRUS BASS', 71: 'STUDIO', 72: 'BRIT 800', 73: 'RECTO1 ORG MDRN', 
      74: 'ANGLE SEVERE 1', 75: 'ANGLE SEVERE 2', 76: 'USA PRE LD1 RED', 77: 'RECTO ORG BRT', 
      78: 'RECTO RED BRT', 79: 'VIBROVERB AA', 80: 'PVH 6160+ LEAD', 81: 'RUMBLE HRM', 
      82: 'MR Z HWY 66', 83: 'SUPER 6G4', 84: '65 BASSMAN BASS', 85: 'FRIEDMAN', 
      86: 'BAND-COMMANDER', 87: 'USA PRE CLEAN', 88: 'TUCANA CLEAN', 89: 'FRIEDMAN SM BOX', 
      90: 'TX STAR', 91: 'USA IIC+', 92: 'THORDENDAL', 93: 'SOLO 99', 94: 'BLUDOJAI', 95: 'HERBIE', 
      96: 'PVH 6160+ CRUNCH', 97: 'SOLO 88 CLEAN', 98: 'JS410', 99: 'JS410 MIDSHIFT', 
      100: 'RUBY ROCKET', 101: 'USA IIC++', 102: 'LEGATO 100', 103: 'HOOK EDGE', 
      104: 'HOOK NO EDGE', 105: 'HOOK CLEAN 1', 106: 'HOOK CLEAN 2', 107: 'SOLO 88', 
      108: 'SPAWN NITROUS', 109: 'SV BASS', 110: 'RECTO2 RED MDRN', 111: 'JP IIC+ YEL/RED', 
      112: 'JP IIC+ GREEN', 113: 'MR Z GHIA', 114: 'MATCHBOX D-30 EF86', 115: 'TRES CORONA', 
      116: 'PVH 6160+ CLEAN', 117: 'ARCHEAN', 118: 'ARCHEAN BRIGHT', 119: 'ARCHEAN CLEAN', 
      120: 'BUDDAH DUOMASTER', 121: 'NULL', 122: 'JMPRE-1 CLN', 123: 'JMPRE-1 CLN BASS', 
      124: 'JMPRE-1 OD1', 125: 'BRIT STUDIO 20', 126: 'BRIT AFS100', 127: 'MATCHBOX D-30', 
      128: 'HERBIE MK3', 129: 'BASSGUY REISSUE', 130: 'REVV PURPLE', 131: 'REVV RED', 
      132: 'REVV GREEN', 133: '5153 RED STEALTH', 134: 'USA CLEAN', 135: 'CLASS-A BRILLIANT', 
      136: 'PLEXI BROWN', 137: 'SUPRO 1695T',
    },
  },
  // DISTORT_FBTYPE -- cache: section 10 id 44, tc=0x10, enum n=69
  // HW-129 Tier-2: amp-model-internal type code. Labels are AM4-native (cache oracle),
  // but arbitrary writes desync the amp model; recommend READ-ONLY exposure.
  'amp.fbtype': {
    block: 'amp', name: 'fbtype',
    pidLow: 0x003a, pidHigh: 0x002c,
    unit: 'enum', displayMin: 0, displayMax: 68,
    enumValues: {
      0: 'BASSGUY', 1: 'PLEXI', 2: 'BRIT 800', 3: 'BRIT 1987x', 4: 'SOLO 100', 5: 'RUMBLE', 
      6: 'XTC', 7: 'JR BLUES', 8: 'RECTO ORG', 9: 'FRYETTE', 10: '6160', 11: 'IDEAL', 12: 'AC-30', 
      13: 'SHIVER OLD', 14: 'CAMERON', 15: 'BRIT JVM', 16: 'TRIPTIK', 17: 'CALI', 18: 'GERMAN V4', 
      19: 'TRIP-TIK', 20: 'WRECKER', 21: 'RECTO RED', 22: 'DEUTSCH WILDE', 23: 'FRIEDMAN', 
      24: 'TUCANA', 25: '5153 100W', 26: 'TERRIER', 27: 'MARK IIC', 28: 'MARK IV RHY', 
      29: 'MATCHBOX', 30: 'SUPER 6G4', 31: 'CONCERT 6G12', 32: 'NULL', 33: 'PLEXI 50W', 
      34: 'SHIVER NEW', 35: 'UBER', 36: 'DIZZY', 37: 'ATOMICA', 38: 'FASTROD', 39: 'TX STAR', 
      40: 'CORNFORD', 41: 'CAPT HOOK', 42: 'AFS100', 43: 'SPAWN NITROUS', 44: 'USA JP IIC+', 
      45: 'SUPREMO TREM', 46: 'BRIT JM45', 47: 'MATCHBOX D-30', 48: 'ARCHEAN', 49: 'DELUXE VERB', 
      50: 'DOUBLE VERB', 51: 'VIBRATO LUX', 52: 'TREMOLO LUX', 53: 'FAS CLASSIC', 54: 'KOMET', 
      55: 'HIPOWER', 56: 'USA SUB BLUES', 57: 'FAS BROOTALZ', 58: 'ENERGYBALL', 59: 'CITRUS RV50', 
      60: 'BASSGUY RI', 61: 'REVV GENERATOR', 62: '5153 50W', 63: '5153 STEALTH', 64: 'JS410', 
      65: 'MARK V', 66: 'BRIT SILVER', 67: 'PLEXI 2204', 68: 'BRIT 6100',
    },
  },
  // DISTORT_PI_RATIO -- cache: section 10 id 45, tc=0x30, display [0..1] step 0.001 (scale 1)
  // HW-129 Tier-1: continuous no-UI advanced register (device ACKs; no front-panel display).
  'amp.pi_ratio': {
    block: 'amp', name: 'pi_ratio',
    pidLow: 0x003a, pidHigh: 0x002d,
    unit: 'ratio', displayMin: 0, displayMax: 1,
  },
  // DISTORT_BIASTYPE -- cache: section 10 id 98, tc=0x10, enum n=3
  // HW-129 Tier-2: amp-model-internal type code. Labels are AM4-native (cache oracle),
  // but arbitrary writes desync the amp model; recommend READ-ONLY exposure.
  'amp.biastype': {
    block: 'amp', name: 'biastype',
    pidLow: 0x003a, pidHigh: 0x0062,
    unit: 'enum', displayMin: 0, displayMax: 2,
    enumValues: {
      0: 'FIXED', 1: 'SHARED CATHODE', 2: 'SPLIT CATHODE',
    },
  },
  // DISTORT_PRECOMPTYPE -- cache: section 10 id 118, tc=0x10, enum n=2
  // HW-129 Tier-2: amp-model-internal type code. Labels are AM4-native (cache oracle),
  // but arbitrary writes desync the amp model; recommend READ-ONLY exposure.
  'amp.precomptype': {
    block: 'amp', name: 'precomptype',
    pidLow: 0x003a, pidHigh: 0x0076,
    unit: 'enum', displayMin: 0, displayMax: 1,
    enumValues: {
      0: 'AUTHENTIC', 1: 'IDEAL',
    },
  },
} as const satisfies Record<string, Param>;

/**
 * Cache-oracle corrections/refinements for shipped GLOBAL (system) params
 * (pidLow 0x01, cache section 1). Keys match the shipped KNOWN_PARAMS keys, so
 * spreading AFTER the shipped entries replaces them. Entries already
 * cache-exact are omitted. Withheld despite cache data (see findings doc):
 * global.delayspill, global.tuneraccidentals.
 */
export const SYSTEM_PARAM_UPDATES = {
  // cache: section 1 id 14, tc=0x1d, enum n=4
  // shipped placeholder was count [0..127]; cache says this is an enum
  'global.tunermute': {
    block: 'global', name: 'tunermute',
    pidLow: 0x0001, pidHigh: 0x000e,
    unit: 'enum', displayMin: 0, displayMax: 3,
    enumValues: {
      0: 'Auto In', 1: 'Auto Out', 2: 'Manual In', 3: 'Manual Out',
    },
    displayLabel: 'Mute Type',
  },
  // cache: section 1 id 16, tc=0x1d, enum n=2
  // shipped placeholder was count [0..127]; cache says this is an enum
  'global.usetuneoffsets': {
    block: 'global', name: 'usetuneoffsets',
    pidLow: 0x0001, pidHigh: 0x0010,
    unit: 'enum', displayMin: 0, displayMax: 1,
    enumValues: {
      0: 'OFF', 1: 'ON',
    },
    displayLabel: 'Use Offsets',
  },
  // cache: section 1 id 17, tc=0x37, display [-25..25] step 0.05 (scale 1)
  // tc unit-family 7 unmapped; cents inferred from range/step and tuner context, UNCONFIRMED
  // shipped was semitones [-1..1]
  'global.offset1': {
    block: 'global', name: 'offset1',
    pidLow: 0x0001, pidHigh: 0x0011,
    unit: 'count', displayMin: -25, displayMax: 25,
    displayUnit: 'cents',
    displayLabel: 'E 1',
  },
  // cache: section 1 id 18, tc=0x37, display [-25..25] step 0.05 (scale 1)
  // tc unit-family 7 unmapped; cents inferred from range/step and tuner context, UNCONFIRMED
  // shipped was semitones [-1..1]
  'global.offset2': {
    block: 'global', name: 'offset2',
    pidLow: 0x0001, pidHigh: 0x0012,
    unit: 'count', displayMin: -25, displayMax: 25,
    displayUnit: 'cents',
    displayLabel: 'B 2',
  },
  // cache: section 1 id 19, tc=0x37, display [-25..25] step 0.05 (scale 1)
  // tc unit-family 7 unmapped; cents inferred from range/step and tuner context, UNCONFIRMED
  // shipped was semitones [-1..1]
  'global.offset3': {
    block: 'global', name: 'offset3',
    pidLow: 0x0001, pidHigh: 0x0013,
    unit: 'count', displayMin: -25, displayMax: 25,
    displayUnit: 'cents',
    displayLabel: 'G 3',
  },
  // cache: section 1 id 20, tc=0x37, display [-25..25] step 0.05 (scale 1)
  // tc unit-family 7 unmapped; cents inferred from range/step and tuner context, UNCONFIRMED
  // shipped was semitones [-1..1]
  'global.offset4': {
    block: 'global', name: 'offset4',
    pidLow: 0x0001, pidHigh: 0x0014,
    unit: 'count', displayMin: -25, displayMax: 25,
    displayUnit: 'cents',
    displayLabel: 'D 4',
  },
  // cache: section 1 id 21, tc=0x37, display [-25..25] step 0.05 (scale 1)
  // tc unit-family 7 unmapped; cents inferred from range/step and tuner context, UNCONFIRMED
  // shipped was semitones [-1..1]
  'global.offset5': {
    block: 'global', name: 'offset5',
    pidLow: 0x0001, pidHigh: 0x0015,
    unit: 'count', displayMin: -25, displayMax: 25,
    displayUnit: 'cents',
    displayLabel: 'A 5',
  },
  // cache: section 1 id 22, tc=0x37, display [-25..25] step 0.05 (scale 1)
  // tc unit-family 7 unmapped; cents inferred from range/step and tuner context, UNCONFIRMED
  // shipped was semitones [-1..1]
  'global.offset6': {
    block: 'global', name: 'offset6',
    pidLow: 0x0001, pidHigh: 0x0016,
    unit: 'count', displayMin: -25, displayMax: 25,
    displayUnit: 'cents',
    displayLabel: 'E 6',
  },
  // cache: section 1 id 45, tc=0x31, display [-40..40] step 0.1 (scale 1)
  // shipped was db [-40..0]
  'global.gate_offset': {
    block: 'global', name: 'gate_offset',
    pidLow: 0x0001, pidHigh: 0x002d,
    unit: 'db', displayMin: -40, displayMax: 40,
    displayLabel: 'Noisegate Offset',
  },
  // cache: section 1 id 47, tc=0x1d, enum n=4
  // shipped placeholder was percent [0..100]; cache says this is an enum
  'global.in1_trim': {
    block: 'global', name: 'in1_trim',
    pidLow: 0x0001, pidHigh: 0x002f,
    unit: 'enum', displayMin: 0, displayMax: 3,
    enumValues: {
      0: '0 dB', 1: '6 dB', 2: '12 dB', 3: '18 dB',
    },
    displayLabel: 'Input Pad',
  },
  // cache: section 1 id 53, tc=0x1d, enum n=2
  // shipped placeholder was count [0..127]; cache says this is an enum
  'global.in1_config': {
    block: 'global', name: 'in1_config',
    pidLow: 0x0001, pidHigh: 0x0035,
    unit: 'enum', displayMin: 0, displayMax: 1,
    enumValues: {
      0: 'MONO (LEFT ONLY)', 1: 'STEREO',
    },
  },
  // cache: section 1 id 57, tc=0x1d, enum n=8
  // shipped placeholder was ms [0..5000]; cache says this is an enum
  'global.fc_hold_timeout': {
    block: 'global', name: 'fc_hold_timeout',
    pidLow: 0x0001, pidHigh: 0x0039,
    unit: 'enum', displayMin: 0, displayMax: 7,
    enumValues: {
      0: '0.25 SECONDS', 1: '0.50 SECONDS', 2: '0.75 SECONDS', 3: '1.00 SECONDS', 
      4: '1.25 SECONDS', 5: '1.50 SECONDS', 6: '1.75 SECONDS', 7: '2.00 SECONDS',
    },
    displayLabel: 'Hold Timeout',
  },
  // cache: section 1 id 58, tc=0x1d, enum n=17
  // shipped placeholder was count [1..16]; cache says this is an enum
  'global.midi_chan': {
    block: 'global', name: 'midi_chan',
    pidLow: 0x0001, pidHigh: 0x003a,
    unit: 'enum', displayMin: 0, displayMax: 16,
    enumValues: {
      0: '1', 1: '2', 2: '3', 3: '4', 4: '5', 5: '6', 6: '7', 7: '8', 8: '9', 9: '10', 10: '11', 
      11: '12', 12: '13', 13: '14', 14: '15', 15: '16', 16: 'OMNI',
    },
    displayLabel: 'MIDI Channel',
  },
  // cache: section 1 id 70, tc=0x2d, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.in1_vol_cc': {
    block: 'global', name: 'in1_vol_cc',
    pidLow: 0x0001, pidHigh: 0x0046,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
    displayLabel: 'Input Volume',
  },
  // cache: section 1 id 71, tc=0x2d, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.out1_vol_cc': {
    block: 'global', name: 'out1_vol_cc',
    pidLow: 0x0001, pidHigh: 0x0047,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
    displayLabel: 'Output Volume',
  },
  // cache: section 1 id 72, tc=0x2d, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.tempo_cc': {
    block: 'global', name: 'tempo_cc',
    pidLow: 0x0001, pidHigh: 0x0048,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
    displayLabel: 'Tap Tempo',
  },
  // cache: section 1 id 73, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.tuner_cc': {
    block: 'global', name: 'tuner_cc',
    pidLow: 0x0001, pidHigh: 0x0049,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'Tuner',
  },
  // cache: section 1 id 74, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.scene_cc': {
    block: 'global', name: 'scene_cc',
    pidLow: 0x0001, pidHigh: 0x004a,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'Scene Select',
  },
  // cache: section 1 id 75, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.scene_incr_cc': {
    block: 'global', name: 'scene_incr_cc',
    pidLow: 0x0001, pidHigh: 0x004b,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'Scene +1',
  },
  // cache: section 1 id 76, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.scene_decr_cc': {
    block: 'global', name: 'scene_decr_cc',
    pidLow: 0x0001, pidHigh: 0x004c,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'Scene -1',
  },
  // cache: section 1 id 77, tc=0x1d, enum n=2
  // shipped placeholder was count [0..127]; cache says this is an enum
  'global.scene_revert': {
    block: 'global', name: 'scene_revert',
    pidLow: 0x0001, pidHigh: 0x004d,
    unit: 'enum', displayMin: 0, displayMax: 1,
    enumValues: {
      0: 'OFF', 1: 'ON',
    },
    displayLabel: 'Default Scene Revert',
  },
  // cache: section 1 id 86, tc=0x1d, enum n=5
  // shipped placeholder was count [1..4]; cache says this is an enum
  'global.default_scene': {
    block: 'global', name: 'default_scene',
    pidLow: 0x0001, pidHigh: 0x0056,
    unit: 'enum', displayMin: 0, displayMax: 4,
    enumValues: {
      0: 'AS SAVED', 1: 'SCENE 1', 2: 'SCENE 2', 3: 'SCENE 3', 4: 'SCENE 4',
    },
    displayLabel: 'Default Scene',
  },
  // cache: section 1 id 88, tc=0x35, display [1..100] step 1 (scale 1)
  // tc says percent-family but cache scale=1 (wire = display 1:1); percent Unit would mis-encode by 100x, so count + cosmetic % suffix
  // shipped was percent [0..100]
  'global.fc_ring_bright_level': {
    block: 'global', name: 'fc_ring_bright_level',
    pidLow: 0x0001, pidHigh: 0x0058,
    unit: 'count', displayMin: 1, displayMax: 100,
    displayUnit: '%',
    displayLabel: 'Switch LED Bright',
  },
  // cache: section 1 id 89, tc=0x35, display [1..100] step 1 (scale 1)
  // tc says percent-family but cache scale=1 (wire = display 1:1); percent Unit would mis-encode by 100x, so count + cosmetic % suffix
  // shipped was percent [0..100]
  'global.fc_ring_dim_level': {
    block: 'global', name: 'fc_ring_dim_level',
    pidLow: 0x0001, pidHigh: 0x0059,
    unit: 'count', displayMin: 1, displayMax: 100,
    displayUnit: '%',
    displayLabel: 'Switch LED Dim',
  },
  // cache: section 1 id 93, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.preset_incr_cc': {
    block: 'global', name: 'preset_incr_cc',
    pidLow: 0x0001, pidHigh: 0x005d,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'Preset +1',
  },
  // cache: section 1 id 94, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.preset_decr_cc': {
    block: 'global', name: 'preset_decr_cc',
    pidLow: 0x0001, pidHigh: 0x005e,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'Preset -1',
  },
  // cache: section 1 id 97, tc=0x61, display [-40..20] step 0.1 (scale 1)
  // shipped was db [-64..24]
  'global.metlevel1': {
    block: 'global', name: 'metlevel1',
    pidLow: 0x0001, pidHigh: 0x0061,
    unit: 'db', displayMin: -40, displayMax: 20,
    displayLabel: 'Metronome Level',
  },
  // cache: section 1 id 99, tc=0x61, display [-40..20] step 0.1 (scale 1)
  // shipped was db [-64..24]
  'global.usblevel1': {
    block: 'global', name: 'usblevel1',
    pidLow: 0x0001, pidHigh: 0x0063,
    unit: 'db', displayMin: -40, displayMax: 20,
    displayLabel: 'USB 1/2 Level',
  },
  // cache: section 1 id 100, tc=0x61, display [-40..20] step 0.1 (scale 1)
  // shipped was db [-64..24]
  'global.usblevel2': {
    block: 'global', name: 'usblevel2',
    pidLow: 0x0001, pidHigh: 0x0064,
    unit: 'db', displayMin: -40, displayMax: 20,
    displayLabel: 'USB 3/4 Level',
  },
  // cache: section 1 id 101, tc=0x61, display [-40..20] step 0.1 (scale 1)
  // shipped was db [-64..24]
  'global.aeslevel': {
    block: 'global', name: 'aeslevel',
    pidLow: 0x0001, pidHigh: 0x0065,
    unit: 'db', displayMin: -40, displayMax: 20,
    displayLabel: 'SPDIF In Level',
  },
  // cache: section 1 id 103, tc=0x1d, enum n=5
  // shipped placeholder was semitones [-12..0]; cache says this is an enum
  'global.downtune': {
    block: 'global', name: 'downtune',
    pidLow: 0x0001, pidHigh: 0x0067,
    unit: 'enum', displayMin: 0, displayMax: 4,
    enumValues: {
      0: 'NONE', 1: '1 SEMITONE', 2: '2 SEMITONES', 3: '3 SEMITONES', 4: '4 SEMITONES',
    },
    displayLabel: 'Downtune',
  },
  // cache: section 1 id 110, tc=0x2d, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.tuner_on_volume': {
    block: 'global', name: 'tuner_on_volume',
    pidLow: 0x0001, pidHigh: 0x006e,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
    displayLabel: 'Tuner on Heel Down CC',
  },
  // cache: section 1 id 111, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.bypass_fx1_cc': {
    block: 'global', name: 'bypass_fx1_cc',
    pidLow: 0x0001, pidHigh: 0x006f,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'FX1 Bypass',
  },
  // cache: section 1 id 112, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.bypass_fx2_cc': {
    block: 'global', name: 'bypass_fx2_cc',
    pidLow: 0x0001, pidHigh: 0x0070,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'FX2 Bypass',
  },
  // cache: section 1 id 113, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.bypass_fx3_cc': {
    block: 'global', name: 'bypass_fx3_cc',
    pidLow: 0x0001, pidHigh: 0x0071,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'FX3 Bypass',
  },
  // cache: section 1 id 114, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.bypass_fx4_cc': {
    block: 'global', name: 'bypass_fx4_cc',
    pidLow: 0x0001, pidHigh: 0x0072,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'FX4 Bypass',
  },
  // cache: section 1 id 115, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.channel_fx1_cc': {
    block: 'global', name: 'channel_fx1_cc',
    pidLow: 0x0001, pidHigh: 0x0073,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'FX1 Channel',
  },
  // cache: section 1 id 116, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.channel_fx2_cc': {
    block: 'global', name: 'channel_fx2_cc',
    pidLow: 0x0001, pidHigh: 0x0074,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'FX2 Channel',
  },
  // cache: section 1 id 117, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.channel_fx3_cc': {
    block: 'global', name: 'channel_fx3_cc',
    pidLow: 0x0001, pidHigh: 0x0075,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'FX3 Channel',
  },
  // cache: section 1 id 118, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.channel_fx4_cc': {
    block: 'global', name: 'channel_fx4_cc',
    pidLow: 0x0001, pidHigh: 0x0076,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'FX4 Channel',
  },
  // cache: section 1 id 119, tc=0x20, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.ext_cc_begin': {
    block: 'global', name: 'ext_cc_begin',
    pidLow: 0x0001, pidHigh: 0x0077,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
    displayLabel: 'External 1',
  },
  // cache: section 1 id 120, tc=0x20, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.ext_cc_begin_1': {
    block: 'global', name: 'ext_cc_begin_1',
    pidLow: 0x0001, pidHigh: 0x0078,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
  },
  // cache: section 1 id 121, tc=0x20, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.ext_cc_begin_2': {
    block: 'global', name: 'ext_cc_begin_2',
    pidLow: 0x0001, pidHigh: 0x0079,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
  },
  // cache: section 1 id 122, tc=0x20, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.ext_cc_begin_3': {
    block: 'global', name: 'ext_cc_begin_3',
    pidLow: 0x0001, pidHigh: 0x007a,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
  },
  // cache: section 1 id 131, tc=0x2d, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.truebypass_cc': {
    block: 'global', name: 'truebypass_cc',
    pidLow: 0x0001, pidHigh: 0x0083,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
    displayLabel: 'AM4 Bypass',
  },
  // cache: section 1 id 132, tc=0x10, enum n=15
  // shipped placeholder was ms [0..5000]; cache says this is an enum
  'global.fs_press_hold1': {
    block: 'global', name: 'fs_press_hold1',
    pidLow: 0x0001, pidHigh: 0x0084,
    unit: 'enum', displayMin: 0, displayMax: 14,
    enumValues: {
      0: 'DISABLED', 1: 'MODE SELECT', 2: 'PRESET MODE', 3: 'SCENE MODE', 4: 'EFFECTS MODE', 
      5: 'TUNER MODE', 6: 'BANK -1', 7: 'BANK +1', 8: 'PRESET -1', 9: 'PRESET +1', 10: 'SCENE -1', 
      11: 'SCENE +1', 12: 'CHANNEL PICKER', 13: 'AMP MODE', 14: 'AM4 BYPASS',
    },
    displayLabel: 'Press & Hold 1',
  },
  // cache: section 1 id 133, tc=0x10, enum n=15
  // shipped placeholder was ms [0..5000]; cache says this is an enum
  'global.fs_press_hold2': {
    block: 'global', name: 'fs_press_hold2',
    pidLow: 0x0001, pidHigh: 0x0085,
    unit: 'enum', displayMin: 0, displayMax: 14,
    enumValues: {
      0: 'DISABLED', 1: 'MODE SELECT', 2: 'PRESET MODE', 3: 'SCENE MODE', 4: 'EFFECTS MODE', 
      5: 'TUNER MODE', 6: 'BANK -1', 7: 'BANK +1', 8: 'PRESET -1', 9: 'PRESET +1', 10: 'SCENE -1', 
      11: 'SCENE +1', 12: 'CHANNEL PICKER', 13: 'AMP MODE', 14: 'AM4 BYPASS',
    },
    displayLabel: 'Press & Hold 2',
  },
  // cache: section 1 id 134, tc=0x10, enum n=15
  // shipped placeholder was ms [0..5000]; cache says this is an enum
  'global.fs_press_hold3': {
    block: 'global', name: 'fs_press_hold3',
    pidLow: 0x0001, pidHigh: 0x0086,
    unit: 'enum', displayMin: 0, displayMax: 14,
    enumValues: {
      0: 'DISABLED', 1: 'MODE SELECT', 2: 'PRESET MODE', 3: 'SCENE MODE', 4: 'EFFECTS MODE', 
      5: 'TUNER MODE', 6: 'BANK -1', 7: 'BANK +1', 8: 'PRESET -1', 9: 'PRESET +1', 10: 'SCENE -1', 
      11: 'SCENE +1', 12: 'CHANNEL PICKER', 13: 'AMP MODE', 14: 'AM4 BYPASS',
    },
    displayLabel: 'Press & Hold 3',
  },
  // cache: section 1 id 135, tc=0x10, enum n=15
  // shipped placeholder was ms [0..5000]; cache says this is an enum
  'global.fs_press_hold4': {
    block: 'global', name: 'fs_press_hold4',
    pidLow: 0x0001, pidHigh: 0x0087,
    unit: 'enum', displayMin: 0, displayMax: 14,
    enumValues: {
      0: 'DISABLED', 1: 'MODE SELECT', 2: 'PRESET MODE', 3: 'SCENE MODE', 4: 'EFFECTS MODE', 
      5: 'TUNER MODE', 6: 'BANK -1', 7: 'BANK +1', 8: 'PRESET -1', 9: 'PRESET +1', 10: 'SCENE -1', 
      11: 'SCENE +1', 12: 'CHANNEL PICKER', 13: 'AMP MODE', 14: 'AM4 BYPASS',
    },
    displayLabel: 'Press & Hold 4',
  },
  // cache: section 1 id 151, tc=0x10, enum n=94
  // shipped enum has 9 values; cache supplies the full device list (94)
  'global.sprk_model': {
    block: 'global', name: 'sprk_model',
    pidLow: 0x0001, pidHigh: 0x0097,
    unit: 'enum', displayMin: 0, displayMax: 93,
    enumValues: {
      0: 'DEFAULT', 1: 'Resistive Load', 2: '1x8 5F1 Tweed', 3: '1x10 Princetone NR', 
      4: '1x10 BF Princetone', 5: '1x10 SF Princetone', 6: '1x12 Tweed Emmi', 
      7: '1x12 Vibrato Lux', 8: '1x12 Deluxe Verb', 9: '1x12 Deluxe Verb RI', 10: '1x12 JR Blues', 
      11: '1x12 Brit G12H55', 12: '1x12 Brit G12H75', 13: '1x12 Div13 CJ11', 14: '1x12 Brit G12T', 
      15: '1x12 V30', 16: '1x12 AC-20 DLX', 17: '1x12 Car Ambler', 18: '1x12 AST BV25', 
      19: '1x15 Vibrato Verb', 20: '1x15 Portabass', 21: '2x10 Super', 22: '2x10 Vibrato Lux', 
      23: '2x12 Bassguy', 24: '2x12 Double Verb', 25: '2x12 Double Verb SF', 
      26: '1x12 Class-A 15W', 27: '2x12 Class-A 30W', 28: '2x12 TX Star', 29: '2x12 Match Chief', 
      30: '1x12 Hot Kitty', 31: '2x12 Jazz 120', 32: '4x10 Bassguy', 33: '4x10 Brit JM45', 
      34: '4x10 Super Verb', 35: '4x10 SV Bass', 36: '4x12 Brit TV', 37: '4x12 Brit Greenback', 
      38: '4x12 Basketweave', 39: '4x12 Brit 800', 40: '4x12 Brit AX', 41: '4x12 Hipower', 
      42: '4x12 USA MC90', 43: '4x12 Recto Large', 44: '4x12 Recto Small', 45: '4x12 Recto Slant', 
      46: '4x12 Recto Straight', 47: '4x12 5153', 48: '4x12 Citrus', 49: '4x12 Rumble', 
      50: '2x12 Lead 80', 51: '4x12 Solo 100', 52: 'Load Box LB-2 UK', 53: 'Load Box LB-2 US', 
      54: '4x12 Friedman', 55: '2x12 Bassbuster', 56: '1x12 Tweed Alnico Blue', 
      57: '4x12 PVH 6160', 58: '4x12 Euro', 59: '2x12 Recto', 60: '2x12 Godzilla', 
      61: '1x12 Tweed C12Q', 62: '1x12 Dirty Shirley EV12L', 63: '1x12 USA Ext EV12L', 
      64: '2x12 Band Commander SRO', 65: '2x12 Guy Tron Alnico Blue', 66: '1x12 G12T-75', 
      67: '2x12 Class-A Greenback', 68: '2x12 Two Stone 1265', 69: '4x12 Lerxst Omega', 
      70: '1x12 Deluxe Oxford', 71: '4x12 Hipower Pete T', 72: '4x12 USA Semi-Open', 
      73: '2x12 Dizzy RV', 74: '4x12 Hipower Lindsey B', 75: '4x12 London Town Tall', 
      76: 'Oxbow Loadbox', 77: 'Double Notes Loadbox', 78: '1x10 Metro Blues', 
      79: '4x10 Bassguy RI', 80: '2x12 Class-A 30W Silver', 81: '2x10 Heart Key', 
      82: '4x12 1960BV', 83: '1x12 Deluxe Tweed', 84: '1x15 Heart Key', 
      85: '2x12 USA C90 Open Back', 86: '1x12 Friedman', 87: '2x12 5153 Stealth', 
      88: '4x12 5153 Stealth', 89: '1x12 Scholz', 90: '1x8 Princetone', 91: '1x12 Black Magick', 
      92: '8x10 SV Bass', 93: 'Suhr Reactive Load',
    },
    displayLabel: 'Speaker Imp. Curve',
  },
  // cache: section 1 id 152, tc=0x2d, enum n=128
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.amp_chan_cc': {
    block: 'global', name: 'amp_chan_cc',
    pidLow: 0x0001, pidHigh: 0x0098,
    unit: 'enum', displayMin: 1, displayMax: 128,
    enumValues: ccLabels(128),
    displayLabel: 'Amp Channel',
  },
  // cache: section 1 id 153, tc=0x2d, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.out_boost_cc': {
    block: 'global', name: 'out_boost_cc',
    pidLow: 0x0001, pidHigh: 0x0099,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
    displayLabel: 'Amp Out Boost',
  },
  // cache: section 1 id 157, tc=0x2d, enum n=127
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.scenesync_cc': {
    block: 'global', name: 'scenesync_cc',
    pidLow: 0x0001, pidHigh: 0x009d,
    unit: 'enum', displayMin: 1, displayMax: 127,
    enumValues: ccLabels(127),
    displayLabel: 'Scene Sync CC#',
  },
  // cache: section 1 id 159, tc=0x2d, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.amp1_vol_cc': {
    block: 'global', name: 'amp1_vol_cc',
    pidLow: 0x0001, pidHigh: 0x009f,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
    displayLabel: 'Amp Block Out Vol',
  },
  // cache: section 1 id 160, tc=0x10, enum n=2
  // shipped placeholder was count [0..127]; cache says this is an enum
  'global.metronome': {
    block: 'global', name: 'metronome',
    pidLow: 0x0001, pidHigh: 0x00a0,
    unit: 'enum', displayMin: 0, displayMax: 1,
    enumValues: {
      0: 'OFF', 1: 'ON',
    },
    displayLabel: 'Metronome',
  },
  // cache: section 1 id 161, tc=0x20, enum n=130
  // shipped placeholder was count [0..127]; cache says this is an enum
  // CC pick list: 1-BASED per the cache min=1/max=count signature (wire value = CC number); unconfirmed on hardware
  'global.metronome_cc': {
    block: 'global', name: 'metronome_cc',
    pidLow: 0x0001, pidHigh: 0x00a1,
    unit: 'enum', displayMin: 1, displayMax: 130,
    enumValues: ccLabels(130),
    displayLabel: 'Metronome',
  },
} as const satisfies Record<string, Param>;

/**
 * Cache records with NO name source (no Ghidra symbol, no XML control).
 * Data only -- names are NOT invented. Amp section-10 low ids match the
 * common per-block row shape (level/mix/balance/bypass...) every section
 * shares; identification needs a probe or a capture, not a guess.
 */
export const UNNAMED_CACHE_RECORDS = [
  { section: 10, id: 1, kind: 'float', tc: 0x75, displayMin: 0, displayMax: 100, scale: 100, step: 0.1 },
  { section: 10, id: 3, kind: 'float', tc: 0xe0, displayMin: 0, displayMax: 1, scale: 1, step: 0 },
  { section: 10, id: 5, kind: 'float', tc: 0xd0, displayMin: 0, displayMax: 0, scale: 0, step: 0 },
  { section: 10, id: 6, kind: 'enum', tc: 0x10, values: ['OFF', 'ON'] },
  { section: 10, id: 7, kind: 'float', tc: 0x00, displayMin: 0, displayMax: 10, scale: 10, step: 0.01 },
  { section: 10, id: 9, kind: 'float', tc: 0x00, displayMin: 0, displayMax: 10, scale: 10, step: 0.01 },
  { section: 1, id: 138, kind: 'float', tc: 0x10, displayMin: 0, displayMax: 5, scale: 1, step: 0 },
] as const;
