/**
 * Generated by scripts/bridge-paramnames-to-xml.ts. Do not hand-edit.
 *
 * Joins the hand-curated paramNames.ts to the XML-derived
 * editorControlLabels.ts and exposes the result as a runtime lookup
 * keyed by (block, snake_case_name). Each entry binds:
 *   - parameterName: AM4-Edit's internal symbolic ID
 *     (e.g. "DISTORT_BRIGHTCAP" — usable as a stable cross-firmware key)
 *   - canonicalLabel: the display label AM4-Edit shows on its UI
 *     (e.g. "Bright Cap" — used in tool descriptions and agent output
 *     so the agent's vocabulary matches what the user reads on screen)
 *
 * This module is a strict refinement layer over paramNames.ts: the
 * underlying wire IDs are unchanged. Only labels and parameterNames
 * are added. Coverage is reached via four passes: display-label
 * match, positional alignment (GEQ/PEQ band patterns), resolver-
 * direct fallback for entries the AM4-Edit dispatcher binds, and a
 * universal block-level register fallback (mix/balance/level/bypass)
 * for wire registers AM4-Edit does not surface in every block UI.
 */

export interface ParameterBridgeEntry {
    block: string;
    name: string;
    parameterName: string;
    canonicalLabel: string;
}

export const PARAMETER_BRIDGE_FIRMWARE = 'AM4-Edit Mar 20 2026 build';

export const PARAMETER_BRIDGE: Readonly<Record<string, Readonly<Record<string, { readonly parameterName: string; readonly canonicalLabel: string }>>>> = {
    amp: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "bass": { parameterName: "DISTORT_BASS", canonicalLabel: "Bass" },
        "bright_cap": { parameterName: "DISTORT_BRIGHTCAP", canonicalLabel: "Bright Cap" },
        "compressor_amount": { parameterName: "DISTORT_COMPRESSION", canonicalLabel: "Amount" },
        "compressor_clarity": { parameterName: "DISTORT_CLARITY", canonicalLabel: "Clarity" },
        "compressor_threshold": { parameterName: "DISTORT_THRESHOLD", canonicalLabel: "Threshold" },
        "depth": { parameterName: "DISTORT_DEPTH", canonicalLabel: "Depth" },
        "gain": { parameterName: "DISTORT_DRIVE", canonicalLabel: "Gain" },
        "geq_band_1": { parameterName: "DISTORT_EQ1", canonicalLabel: "Low" },
        "geq_band_2": { parameterName: "DISTORT_EQ2", canonicalLabel: "Mid" },
        "geq_band_3": { parameterName: "DISTORT_EQ3", canonicalLabel: "Treble" },
        "geq_band_4": { parameterName: "DISTORT_EQ4", canonicalLabel: "Presence" },
        "geq_band_5": { parameterName: "DISTORT_EQ5", canonicalLabel: "1K" },
        "geq_band_6": { parameterName: "DISTORT_EQ6", canonicalLabel: "2K" },
        "geq_band_7": { parameterName: "DISTORT_EQ7", canonicalLabel: "4K" },
        "geq_band_8": { parameterName: "DISTORT_EQ8", canonicalLabel: "8K" },
        "high_treble": { parameterName: "DISTORT_HITREBLE", canonicalLabel: "High Treble" },
        "input_trim": { parameterName: "DISTORT_TRIM", canonicalLabel: "Input Trim" },
        "master": { parameterName: "DISTORT_MASTER", canonicalLabel: "Master" },
        "master_vol_trim": { parameterName: "DISTORT_MVTRIM", canonicalLabel: "Master Vol Trim" },
        "mid": { parameterName: "DISTORT_MID", canonicalLabel: "Mid" },
        "out_boost_level": { parameterName: "BLOCK_OUTBOOSTDB", canonicalLabel: "Out Boost Level" },
        "presence": { parameterName: "DISTORT_PRESENCE", canonicalLabel: "Presence" },
        "treble": { parameterName: "DISTORT_TREBLE", canonicalLabel: "Treble" },
        "type": { parameterName: "DISTORT_TYPE", canonicalLabel: "Type" },
    },
    chorus: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "depth": { parameterName: "CHORUS_DEPTH", canonicalLabel: "Depth" },
        "drive": { parameterName: "CHORUS_DRIVE", canonicalLabel: "Drive" },
        "high_cut": { parameterName: "CHORUS_HICUT", canonicalLabel: "High Cut" },
        "lfo_depth_2": { parameterName: "CHORUS_SPREAD", canonicalLabel: "Stereo Spread" },
        "lfo_freq": { parameterName: "CHORUS_LOWCUT", canonicalLabel: "Low Cut" },
        "lfo_phase_pct": { parameterName: "CHORUS_WIDTH", canonicalLabel: "Right\nTime Ratio" },
        "lfo_rate": { parameterName: "CHORUS_RATE2", canonicalLabel: "Rate Right" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "number_of_voices": { parameterName: "CHORUS_VOICES", canonicalLabel: "Number of Voices" },
        "rate": { parameterName: "CHORUS_RATE", canonicalLabel: "Rate" },
        "type": { parameterName: "CHORUS_TYPE", canonicalLabel: "CHORUS_TYPE" },
        "width": { parameterName: "CHORUS_DEPTH2", canonicalLabel: "LFO 2 Depth" },
    },
    compressor: {
        "attack": { parameterName: "COMP_ATTACK", canonicalLabel: "Attack" },
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "drive": { parameterName: "COMP_DRIVE", canonicalLabel: "Drive" },
        "emphasis": { parameterName: "COMP_EMPHASIS", canonicalLabel: "Emphasis" },
        "look_ahead_time": { parameterName: "COMP_DELAYTIME", canonicalLabel: "Look-Ahead Time" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "ratio": { parameterName: "COMP_RATIO", canonicalLabel: "Ratio" },
        "release": { parameterName: "COMP_RELEASE", canonicalLabel: "Release Time" },
        "sidechain_emphasis_freq": { parameterName: "COMP_EMPHFREQ", canonicalLabel: "Emphasis Freq" },
        "sidechain_frequency": { parameterName: "COMP_FREQ", canonicalLabel: "Frequency" },
        "sidechain_gain": { parameterName: "COMP_GAIN", canonicalLabel: "Gain" },
        "sidechain_high_cut": { parameterName: "COMP_HIGHCUT", canonicalLabel: "High Cut" },
        "sidechain_low_cut": { parameterName: "COMP_LOWCUT", canonicalLabel: "Low Cut" },
        "sidechain_q": { parameterName: "COMP_Q", canonicalLabel: "Q" },
        "threshold": { parameterName: "COMP_THRESH", canonicalLabel: "Threshold" },
        "type": { parameterName: "COMP_TYPE", canonicalLabel: "COMP_TYPE" },
    },
    delay: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "bit_reduction": { parameterName: "DELAY_BITREDUCE", canonicalLabel: "Bit Reduction" },
        "compander_threshold": { parameterName: "DELAY_COMPTHRESH", canonicalLabel: "Threshold" },
        "compander_time": { parameterName: "DELAY_COMPTIME", canonicalLabel: "Time" },
        "diffusion_time": { parameterName: "DELAY_DIFFTIME", canonicalLabel: "Diffusion Time" },
        "diffusor": { parameterName: "DELAY_DIFFUSE", canonicalLabel: "Diffuser" },
        "ducker_release": { parameterName: "DELAY_RELEASE", canonicalLabel: "Release" },
        "ducker_threshold": { parameterName: "DELAY_THRESH", canonicalLabel: "Threshold" },
        "ducking": { parameterName: "DELAY_ATTEN", canonicalLabel: "Ducking" },
        "eq_freq_1": { parameterName: "DELAY_FREQ1", canonicalLabel: "Frequency 1" },
        "eq_freq_2": { parameterName: "DELAY_FREQ2", canonicalLabel: "Frequency 2" },
        "eq_gain_1": { parameterName: "DELAY_GAIN1", canonicalLabel: "Gain 1" },
        "eq_gain_2": { parameterName: "DELAY_GAIN2", canonicalLabel: "Gain 2" },
        "eq_q_1": { parameterName: "DELAY_Q1", canonicalLabel: "Q 1" },
        "eq_q_2": { parameterName: "DELAY_Q2", canonicalLabel: "Q 2" },
        "eq_q_high_low": { parameterName: "DELAY_FILTERQ", canonicalLabel: "Q (High + Low)" },
        "feedback": { parameterName: "DELAY_FEED", canonicalLabel: "Feedback" },
        "feedback_r": { parameterName: "DELAY_FEEDR", canonicalLabel: "Feedback R" },
        "high_cut": { parameterName: "DELAY_HICUT", canonicalLabel: "High Cut" },
        "hold_feedback": { parameterName: "DELAY_HOLDFDBK", canonicalLabel: "Hold Feedback" },
        "input_gain": { parameterName: "DELAY_GAIN", canonicalLabel: "Input Gain" },
        "lfo_depth": { parameterName: "DELAY_DIFFDEPTH", canonicalLabel: "LFO Depth" },
        "lfo_rate": { parameterName: "DELAY_DIFFRATE", canonicalLabel: "LFO Rate" },
        "low_cut": { parameterName: "DELAY_LOCUT", canonicalLabel: "Low Cut" },
        "lr_time_ratio": { parameterName: "DELAY_RATIO", canonicalLabel: "L/R Time Ratio" },
        "master_feedback": { parameterName: "DELAY_MSTRFDBK", canonicalLabel: "Master Feedback" },
        "master_time": { parameterName: "DELAY_MSTRTIME", canonicalLabel: "Master Time" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "motor_speed": { parameterName: "DELAY_SPEED", canonicalLabel: "Motor\nSpeed" },
        "stack_feedback": { parameterName: "DELAY_STACKFDBK", canonicalLabel: "Stack Feedback" },
        "stereo_spread": { parameterName: "DELAY_SPREAD", canonicalLabel: "Stereo Spread" },
        "time": { parameterName: "DELAY_TIME", canonicalLabel: "Time" },
        "type": { parameterName: "DELAY_MODEL", canonicalLabel: "DELAY_MODEL" },
    },
    drive: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "bass": { parameterName: "FUZZ_LOW", canonicalLabel: "Bass" },
        "bit_reduce": { parameterName: "FUZZ_BITREDUCE", canonicalLabel: "Bit Reduce" },
        "drive": { parameterName: "FUZZ_DRIVE", canonicalLabel: "Drive" },
        "geq_band_1": { parameterName: "FUZZ_EQ1", canonicalLabel: "100" },
        "geq_band_10": { parameterName: "FUZZ_EQ10", canonicalLabel: "6400" },
        "geq_band_2": { parameterName: "FUZZ_EQ2", canonicalLabel: "160" },
        "geq_band_3": { parameterName: "FUZZ_EQ3", canonicalLabel: "250" },
        "geq_band_4": { parameterName: "FUZZ_EQ4", canonicalLabel: "400" },
        "geq_band_5": { parameterName: "FUZZ_EQ5", canonicalLabel: "640" },
        "geq_band_6": { parameterName: "FUZZ_EQ6", canonicalLabel: "1000" },
        "geq_band_7": { parameterName: "FUZZ_EQ7", canonicalLabel: "1600" },
        "geq_band_8": { parameterName: "FUZZ_EQ8", canonicalLabel: "2500" },
        "geq_band_9": { parameterName: "FUZZ_EQ9", canonicalLabel: "4000" },
        "high_cut": { parameterName: "FUZZ_HICUT", canonicalLabel: "High Cut" },
        "high_mid": { parameterName: "FUZZ_HIMID", canonicalLabel: "High Mid" },
        "level": { parameterName: "FUZZ_LEVEL", canonicalLabel: "Level" },
        "low_cut": { parameterName: "FUZZ_LOCUT", canonicalLabel: "Low Cut" },
        "mid": { parameterName: "FUZZ_MID", canonicalLabel: "Mid" },
        "mid_freq": { parameterName: "FUZZ_MIDFREQ", canonicalLabel: "Mid Frequency" },
        "mix": { parameterName: "FUZZ_MIX", canonicalLabel: "Blend" },
        "tone": { parameterName: "FUZZ_TONE", canonicalLabel: "Tone" },
        "treble": { parameterName: "FUZZ_TREBLE", canonicalLabel: "Treble" },
        "type": { parameterName: "FUZZ_TYPE", canonicalLabel: "FUZZ_TYPE" },
    },
    enhancer: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "depth": { parameterName: "ENHANCER_DEPTH", canonicalLabel: "Depth" },
        "high_cut": { parameterName: "ENHANCER_HICUT", canonicalLabel: "High Cut" },
        "low_cut": { parameterName: "ENHANCER_LOWCUT", canonicalLabel: "Low Cut" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "type": { parameterName: "ENHANCER_TYPE", canonicalLabel: "ENHANCER_TYPE" },
        "width": { parameterName: "ENHANCER_WIDTH", canonicalLabel: "Width" },
    },
    filter: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "feedback": { parameterName: "FILTER_FEEDBACK", canonicalLabel: "Feedback" },
        "freq": { parameterName: "FILTER_FREQ", canonicalLabel: "Frequency" },
        "high_cut": { parameterName: "FILTER_HICUT", canonicalLabel: "High Cut" },
        "low_cut": { parameterName: "FILTER_LOWCUT", canonicalLabel: "Low Cut" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "order": { parameterName: "FILTER_APORDER", canonicalLabel: "Order" },
        "sensitivity": { parameterName: "FILTER_SENS", canonicalLabel: "Sensitivity" },
        "type": { parameterName: "FILTER_TYPE", canonicalLabel: "Type" },
    },
    flanger: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "depth": { parameterName: "FLANGER_DEPTH", canonicalLabel: "Depth" },
        "feedback": { parameterName: "FLANGER_FEEDBACK", canonicalLabel: "Feedback" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "rate": { parameterName: "FLANGER_RATE", canonicalLabel: "Rate" },
        "type": { parameterName: "FLANGER_TYPE", canonicalLabel: "FLANGER_TYPE" },
    },
    gate: {
        "attack": { parameterName: "GATE_ATTACK", canonicalLabel: "Attack" },
        "attenuation": { parameterName: "GATE_RANGE", canonicalLabel: "Attenuation" },
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "hold": { parameterName: "GATE_HOLD", canonicalLabel: "Hold" },
        "release": { parameterName: "GATE_RELEASE", canonicalLabel: "Release" },
        "threshold": { parameterName: "GATE_THRESH", canonicalLabel: "Threshold" },
        "type": { parameterName: "GATE_TYPE", canonicalLabel: "GATE_TYPE" },
    },
    geq: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "band_1": { parameterName: "GEQ_GAIN1", canonicalLabel: "100" },
        "band_10": { parameterName: "GEQ_GAIN10", canonicalLabel: "16k" },
        "band_2": { parameterName: "GEQ_GAIN2", canonicalLabel: "160" },
        "band_3": { parameterName: "GEQ_GAIN3", canonicalLabel: "400" },
        "band_4": { parameterName: "GEQ_GAIN4", canonicalLabel: "800" },
        "band_5": { parameterName: "GEQ_GAIN5", canonicalLabel: "500" },
        "band_6": { parameterName: "GEQ_GAIN6", canonicalLabel: "1k" },
        "band_7": { parameterName: "GEQ_GAIN7", canonicalLabel: "2k" },
        "band_8": { parameterName: "GEQ_GAIN8", canonicalLabel: "4k" },
        "band_9": { parameterName: "GEQ_GAIN9", canonicalLabel: "8k" },
        "master_q": { parameterName: "GEQ_MASTERQ", canonicalLabel: "Master Q" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "type": { parameterName: "GEQ_TYPE", canonicalLabel: "GEQ_TYPE" },
    },
    peq: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "channel_1_frequency": { parameterName: "PEQ_FREQ1", canonicalLabel: "Freq 1" },
        "channel_1_gain": { parameterName: "PEQ_GAIN1", canonicalLabel: "Gain 1" },
        "channel_1_q": { parameterName: "PEQ_Q1", canonicalLabel: "Q1" },
        "channel_2_frequency": { parameterName: "PEQ_FREQ2", canonicalLabel: "Freq 2" },
        "channel_2_gain": { parameterName: "PEQ_GAIN2", canonicalLabel: "Gain 2" },
        "channel_2_q": { parameterName: "PEQ_Q2", canonicalLabel: "Q2" },
        "channel_3_frequency": { parameterName: "PEQ_FREQ3", canonicalLabel: "Freq 3" },
        "channel_3_gain": { parameterName: "PEQ_GAIN3", canonicalLabel: "Gain 3" },
        "channel_3_q": { parameterName: "PEQ_Q3", canonicalLabel: "Q3" },
        "channel_4_frequency": { parameterName: "PEQ_FREQ4", canonicalLabel: "Freq 4" },
        "channel_4_gain": { parameterName: "PEQ_GAIN4", canonicalLabel: "Gain 4" },
        "channel_4_q": { parameterName: "PEQ_Q4", canonicalLabel: "Q4" },
        "channel_5_frequency": { parameterName: "PEQ_FREQ5", canonicalLabel: "Freq 5" },
        "channel_5_gain": { parameterName: "PEQ_GAIN5", canonicalLabel: "Gain 5" },
        "channel_5_q": { parameterName: "PEQ_Q5", canonicalLabel: "Q5" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
    },
    phaser: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "feedback": { parameterName: "PHASER_FEEDBACK", canonicalLabel: "Feedback" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "rate": { parameterName: "PHASER_RATE", canonicalLabel: "Rate" },
        "type": { parameterName: "PHASER_TYPE", canonicalLabel: "Type" },
    },
    reverb: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "shift_1": { parameterName: "REVERB_SHIFT1", canonicalLabel: "Voice 1 Shift" },
        "shift_2": { parameterName: "REVERB_SHIFT2", canonicalLabel: "Voice 2 Shift" },
        "size": { parameterName: "REVERB_SIZE", canonicalLabel: "Size" },
        "spring_tone": { parameterName: "REVERB_TONE", canonicalLabel: "Tone" },
        "springs": { parameterName: "REVERB_NUMSPRINGS", canonicalLabel: "# of Springs" },
        "time": { parameterName: "REVERB_TIME", canonicalLabel: "Time" },
        "type": { parameterName: "REVERB_TYPE", canonicalLabel: "REVERB_TYPE" },
    },
    rotary: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "drive": { parameterName: "ROTARY_DRIVE", canonicalLabel: "Drive" },
        "high_depth": { parameterName: "ROTARY_HFDEPTH", canonicalLabel: "High Depth" },
        "high_level": { parameterName: "ROTARY_HFLEVEL", canonicalLabel: "High Level" },
        "high_time_constant": { parameterName: "ROTARY_HIGHTIME", canonicalLabel: "High Time Constant" },
        "low_depth": { parameterName: "ROTARY_LFDEPTH", canonicalLabel: "Low Depth" },
        "low_rate_multiplier": { parameterName: "ROTARY_LOWRATE", canonicalLabel: "Low Rate Multiplier" },
        "low_time_constant": { parameterName: "ROTARY_LOWTIME", canonicalLabel: "Low Time Constant" },
        "mic_distance": { parameterName: "ROTARY_MICDIST", canonicalLabel: "Mic Distance" },
        "mic_spacing": { parameterName: "ROTARY_WIDTH", canonicalLabel: "Mic\nSpacing" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "rate": { parameterName: "ROTARY_RATE", canonicalLabel: "Rate" },
        "rotor_length": { parameterName: "ROTARY_HFLENGTH", canonicalLabel: "Rotor Length" },
        "stereo_spread": { parameterName: "ROTARY_SPREAD", canonicalLabel: "Stereo Spread" },
    },
    tremolo: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "depth": { parameterName: "TREMOLO_DEPTH", canonicalLabel: "Depth" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "rate": { parameterName: "TREMOLO_RATE", canonicalLabel: "Rate" },
        "type": { parameterName: "TREMOLO_TYPE", canonicalLabel: "Type" },
    },
    volpan: {
        "attack": { parameterName: "VOLUME_ATTACK", canonicalLabel: "Attack" },
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "mode": { parameterName: "VOLUME_TYPE", canonicalLabel: "VOLUME_TYPE" },
        "threshold": { parameterName: "VOLUME_THRESHOLD", canonicalLabel: "Threshold" },
    },
    wah: {
        "balance": { parameterName: "BLOCK_PAN", canonicalLabel: "Balance" },
        "drive": { parameterName: "WAH_DRIVE", canonicalLabel: "Drive" },
        "fat": { parameterName: "WAH_MIX", canonicalLabel: "Fat" },
        "graphic_eq_band_1": { parameterName: "WAH_EQ1", canonicalLabel: "160" },
        "graphic_eq_band_2": { parameterName: "WAH_EQ2", canonicalLabel: "250" },
        "graphic_eq_band_3": { parameterName: "WAH_EQ3", canonicalLabel: "400" },
        "graphic_eq_band_4": { parameterName: "WAH_EQ4", canonicalLabel: "640" },
        "graphic_eq_band_5": { parameterName: "WAH_EQ5", canonicalLabel: "1000" },
        "graphic_eq_band_6": { parameterName: "WAH_EQ6", canonicalLabel: "1600" },
        "graphic_eq_band_7": { parameterName: "WAH_EQ7", canonicalLabel: "2500" },
        "graphic_eq_band_8": { parameterName: "WAH_EQ8", canonicalLabel: "4000" },
        "inductor_bias": { parameterName: "WAH_BIAS", canonicalLabel: "Inductor Bias" },
        "low_cut_frequency": { parameterName: "WAH_HPF", canonicalLabel: "Low Cut Frequency" },
        "max_frequency": { parameterName: "WAH_FSTOP", canonicalLabel: "Maximum Frequency" },
        "min_frequency": { parameterName: "WAH_FSTART", canonicalLabel: "Minimum Frequency" },
        "mix": { parameterName: "BLOCK_MIX", canonicalLabel: "Mix" },
        "q_resonance": { parameterName: "WAH_Q", canonicalLabel: "Resonance" },
        "q_tracking": { parameterName: "WAH_TRACK", canonicalLabel: "Q Tracking " },
        "type": { parameterName: "WAH_TYPE", canonicalLabel: "WAH_TYPE" },
        "wah_control": { parameterName: "WAH_CONTROL", canonicalLabel: "Wah Control" },
    },
};

/**
 * Resolve the AM4-Edit canonical display label and symbolic
 * parameterName for a (block, name) pair from paramNames.ts.
 *
 * Returns undefined if the (block, name) has no XML correspondence
 * yet — the caller should fall back to the snake_case name from
 * paramNames.ts as the display label.
 */
export function resolveBridge(block: string, name: string):
    | { parameterName: string; canonicalLabel: string }
    | undefined
{
    return PARAMETER_BRIDGE[block]?.[name];
}

/** Canonical label for a (block, name), or the original `name`. */
export function preferredDisplayLabel(block: string, name: string): string {
    return PARAMETER_BRIDGE[block]?.[name]?.canonicalLabel ?? name;
}