/**
 * Generated by scripts/gen-paramnames-from-resolver.ts — do not hand-edit.
 *
 * Friendly parameter names synthesized from the resolver MISSING set.
 * Each entry is a (cache_id → snake_case_name) binding for a wire address
 * the AM4-Edit variant resolver knows about but `paramNames.ts` has no
 * hand-curated entry for.
 *
 * Source authority chain (firmware-truth):
 *   1. AM4-Edit.exe variant resolver (FUN_1402e3da0)
 *      -> src/protocol/variantResolverTables.ts
 *      provides (block, parameterName, cache_id) bindings.
 *   2. AM4-Edit.exe BinaryData ZIP -> __block_layout*.xml
 *      -> src/protocol/editorControlLabels.ts
 *      provides parameterName -> canonical display label.
 *   3. AM4-Edit metadata cache (effectDefinitions_15_2p0.cache)
 *      -> samples/captured/decoded/cache-section{2,3}.json
 *      provides typecode / a / b / c -> unit + display range.
 *
 * Merge with the hand-curated `paramNames.ts` happens in
 * `scripts/gen-params-from-cache.ts`. Resolver-derived entries are
 * firmware-truth (from AM4-Edit.exe's per-variant dispatcher), so they
 * win on (block, cache_id) → parameterName conflicts. Hand-curated
 * entries from `paramNames.ts` were seeded from hardware captures —
 * messy and occasionally mis-bound — so they yield to the resolver
 * where the two disagree. For THIS regen, the generator only emits to
 * cache_ids where `paramNames.ts` has no entry (the diff's MISSING
 * set), so there is no actual conflict to resolve; the conflict-
 * resolution rule applies to future broader regenerations.
 *
 * Coverage as of regen: 158 new wire-bound friendly names
 * across 11 blocks.
 *
 * Comment beside each entry shows: <canonicalLabel> (<parameterName>) —
 * the canonical AM4-Edit display label as users will see it on screen,
 * paired with the firmware symbolic ID for cross-reference.
 */
import type { ParamNameEntry } from './paramNames.js';

export const GENERATED_PARAM_NAMES: Readonly<Record<string, Readonly<Record<number, ParamNameEntry>>>> = {
  amp: {
    21: 'proximity', // Proximity (CABINET_PROXIMITY2)
    38: 'master_vol_cap', // Master Vol Cap (DISTORT_MVCAP)
    51: 'hi_reso', // Hi Reso (DISTORT_SPKRHFGAIN)
    57: 'drive', // Drive (DISTORT_SPKRDRIVE)
    71: 'distance', // Distance (CABINET_DYNACAB_Z1)
    72: 'distance_dynacab_z2', // Distance (CABINET_DYNACAB_Z2)
    79: 'frequency', // Frequency (DISTORT_INEQFREQ)
    81: 'overdrive', // Overdrive (DISTORT_DRIVE2)
    86: 'definition', // Definition (DISTORT_DEFINITION)
    87: 'compression', // Compression (DISTORT_CFTHRESH)
    88: 'cfgrid', // DISTORT_CFGRID
    90: 'high_cut', // High Cut (DISTORT_HICUT)
    91: 'dynpres', // DISTORT_DYNPRES
    92: 'dyndepth', // DISTORT_DYNDEPTH
    96: 'tremfreq', // DISTORT_TREMFREQ
    97: 'tremdepth', // DISTORT_TREMDEPTH
    100: 'cathode_resistance', // Cathode Resistance (DISTORT_CBRATIO)
    102: 'dynimp', // DISTORT_DYNIMP
    106: 'indynamics', // DISTORT_INDYNAMICS
    110: 'gridhardness', // DISTORT_GRIDHARDNESS
    114: 'triode2extime', // DISTORT_TRIODE2EXTIME
    115: 'triode2rectime', // DISTORT_TRIODE2RECTIME
    119: 'triode1ratio', // DISTORT_TRIODE1RATIO
    120: 'cfhardness', // DISTORT_CFHARDNESS
    124: 'resolution', // DISTORT_RESOLUTION
    125: 'vccmon', // B+ (DISTORT_VCCMON)
    126: 'gain_gainmon', // Gain (DISTORT_GAINMON)
    127: 'mdmon', // DISTORT_MDMON
    128: 'indynmon', // DISTORT_INDYNMON
    137: 'headroom', // HEADROOM (DISTORT_VPLATEMON)
    138: 'presence_prepresence', // Presence (DISTORT_PREPRESENCE)
    140: 'high_cut_pahicut', // High Cut (DISTORT_PAHICUT)
    145: 'overdrive_volume', // Overdrive Volume (DISTORT_GLOBALMASTER)
    151: 'disablecabsync', // DISTORT_DISABLECABSYNC
  },
  drive: {
    15: 'slew_rate_slew', // Slew Rate (FUZZ_SLEW)
    19: 'bias_bias', // Bias (FUZZ_BIAS)
    40: 'diode_quantity_pdqty', // Diode+ Quantity (FUZZ_PDQTY)
    42: 'diode_quantity', // Diode- Quantity (FUZZ_NDQTY)
    43: 'dry_level', // Dry Level (FUZZ_DRYGAIN)
    44: 'bass_bass', // Bass (FUZZ_BASS)
    49: 'drive_drive2', // Drive (FUZZ_DRIVE2)
  },
  reverb: {
    13: 'high_decay', // High Decay (REVERB_HFRATIO)
    14: 'scattering', // Scattering (REVERB_DIFFUSION)
    16: 'reverbdelay', // REVERB_REVERBDELAY
    17: 'early_level', // Early Level (REVERB_EARLYLEVEL)
    18: 'late_level', // Late Level  (REVERB_REVERBLEVEL)
    21: 'depth', // Depth (REVERB_DEPTH)
    22: 'rate', // Rate (REVERB_RATE)
    25: 'diffusion', // Diffusion (REVERB_INPDIFF)
    26: 'diffusion_time', // Diffusion Time (REVERB_INDIFFTIME)
    29: 'pickup_spacing', // Pickup Spacing (REVERB_WIDTH)
    30: 'frequency_1', // Frequency 1 (REVERB_FREQ1)
    31: 'frequency_2', // Frequency 2 (REVERB_FREQ2)
    32: 'q_1', // Q 1 (REVERB_Q1)
    33: 'q_2', // Q 2 (REVERB_Q2)
    34: 'gain_1', // Gain 1 (REVERB_GAIN1)
    35: 'gain_2', // Gain 2 (REVERB_GAIN2)
    37: 'low_decay', // Low Decay (REVERB_LFTIME)
    38: 'xover_frequency', // Xover Frequency (REVERB_LFXOVER)
    41: 'threshold', // Threshold (REVERB_THRESH)
    42: 'release_time', // Release Time (REVERB_RELEASE)
    43: 'early_diffusion', // Early Diffusion (REVERB_EARLYDIFF)
    44: 'early_diff_time', // Early Diff Time (REVERB_EARLYDIFFTIME)
    45: 'early_decay', // Early Decay (REVERB_EARLYDECAY)
    46: 'late_input_mix', // Late Input Mix (REVERB_EARLYSEND)
    49: 'basetype', // REVERB_BASETYPE
    50: 'lfo_phase', // LFO Phase (REVERB_LFOPHASE)
    55: 'pitch_mix', // Pitch Mix (REVERB_PITCHMIX)
    58: 'pitch_feedback', // Pitch Feedback (REVERB_PITCHFDBK)
    60: 'splice_time', // Splice Time (REVERB_PITCHTIME)
    62: 'pitch_modulation', // Pitch Modulation (REVERB_PITCHMOD)
    63: 'voice_balance', // Voice Balance (REVERB_PITCHBAL)
    65: 'feedback', // Feedback (REVERB_PREDLYFDBK)
    66: 'echo_mix', // Echo Mix (REVERB_PREDLYMIX)
    67: 'pitch_high_cut', // Pitch High Cut (REVERB_PITCHLPF)
    69: 'tonetype', // REVERB_TONETYPE
    71: 'low_cut_q', // Low Cut Q (REVERB_LOWQ)
    72: 'high_cut_q', // High Cut Q (REVERB_HIGHQ)
  },
  delay: {
    15: 'tempo_1', // Tempo 1 (MULTITAP_TEMPO1)
    17: 'echo_pan', // Echo Pan (DELAY_DELAYPAN)
    22: 'mod_rate', // Mod Rate (DELAY_RATE1)
    23: 'rate', // Rate (DELAY_RATE2)
    24: 'mod_depth', // Mod Depth (DELAY_DEPTH1)
    25: 'mod_depth_depth2', // Mod Depth (DELAY_DEPTH2)
    30: 'time_r', // Time R (DELAY_TIMER)
    34: 'rotation', // Rotation (DELAY_FEEDLR)
    35: 'lfo_1_type', // LFO 1 Type (MULTITAP_LFOTYPE1)
    36: 'level_l', // Level L (DELAY_LEVELL)
    37: 'level_r', // Level R (DELAY_LEVELR)
    38: 'pan_l', // Pan L (DELAY_PANL)
    39: 'pan_r', // Pan R (DELAY_PANR)
    40: 'modulation_phase', // Modulation Phase (DELAY_LFO1PHASE)
    41: 'lfo_phase', // LFO Phase (DELAY_LFO2PHASE)
    42: 'crossfade_time', // Crossfade Time (DELAY_SPLICETIME)
    56: 'sweep_rate', // Sweep Rate (DELAY_RATE3)
    58: 'sweep_phase', // Sweep Phase (DELAY_LFO3PHASE)
    60: 'sweep_start_freq', // Sweep Start Freq (DELAY_FSTART)
    61: 'sweep_stop_freq', // Sweep Stop Freq (DELAY_FSTOP)
    62: 'sweep_resonance', // Sweep Resonance (DELAY_Q)
    73: 'right_post_delay', // Right Post Delay (DELAY_OFFSET)
    82: 'pan_rate', // Pan Rate (DELAY_RATE4)
    84: 'pan_depth', // Pan Depth (DELAY_DEPTH4)
    85: 'lfo_phase_lfo4phase', // LFO Phase (DELAY_LFO4PHASE)
  },
  chorus: {
    28: 'left_depth', // Left Depth (CHORUS_DEPTHL)
    29: 'center_depth', // Center Depth (CHORUS_DEPTHC)
    30: 'right_depth', // Right Depth (CHORUS_DEPTHR)
  },
  flanger: {
    16: 'dry_delay', // Dry Delay (FLANGER_DRYDELAY)
    19: 'smooth_steps', // Smooth Steps (FLANGER_LFOFILTER)
    23: 'high_cut', // High Cut (FLANGER_LPFREQ)
    24: 'drive', // Drive (FLANGER_DRIVE)
    25: 'low_cut', // Low Cut (FLANGER_HPFREQ)
    26: 'stereo_spread', // Stereo Spread (FLANGER_SPREAD)
    30: 'bass_focus', // Bass Focus (FLANGER_FOCUS)
    32: 'min_time', // Min Time (FLANGER_TMIN)
    33: 'max_time', // Max Time (FLANGER_TMAX)
    35: 'vpo_exponent', // VPO Exponent (FLANGER_VCOK)
  },
  phaser: {
    17: 'min_frequency', // Min Frequency (PHASER_FMIN)
    18: 'max_frequency', // Max Frequency (PHASER_FMAX)
    20: 'bias', // Bias (PHASER_BIAS)
    22: 'feedback_point', // Feedback Point (PHASER_FBTAP)
    23: 'tone', // Tone (PHASER_TONE)
    25: 'q', // Q (PHASER_Q)
    29: 'shape_vcrk', // Shape (PHASER_VCRK)
    30: 'shape', // Shape (PHASER_LFOBETA)
    31: 'high_cut', // High Cut (PHASER_LFOLPF)
    32: 'attack', // Attack (PHASER_ATTACK)
    33: 'release', // Release (PHASER_RELEASE)
    35: 'low_cut', // Low Cut (PHASER_HPF)
    36: 'high_cut_lpf', // High Cut (PHASER_LPF)
  },
  compressor: {
    20: 'compression', // Compression (COMP_SUSTAIN)
    24: 'dynamics', // Dynamics (COMP_DYNAMICS)
    33: 'threshold_thresh2', // Threshold (COMP_THRESH2)
    36: 'ratio_compansion', // Ratio (COMP_COMPANSION)
    37: 'time', // Time (COMP_COMPTIME)
    38: 'transients', // Transients (COMP_COMPMATCH)
    40: 'tone', // Tone (COMP_TONE)
  },
  filter: {
    12: 'q', // Q (FILTER_Q)
    13: 'gain', // Gain (FILTER_GAIN)
    15: 'pan_left', // Pan Left (FILTER_PANL)
    16: 'pan_right', // Pan Right (FILTER_PANR)
    20: 'delay_time', // Delay Time (FILTER_COMBTIME)
    24: 'rate', // Rate (FILTER_LFOFREQ)
    25: 'lfo_duty', // LFO Duty (FILTER_LFODUTY)
    26: 'mod_frequency', // Mod Frequency (FILTER_MODFREQ)
    30: 'resonance', // Resonance (FILTER_EVFQ)
    31: 'start_frequency', // Start Frequency (FILTER_START)
    32: 'stop_frequency', // Stop Frequency (FILTER_STOP)
    34: 'attack_time', // Attack Time (FILTER_ATTACK)
    35: 'release_time', // Release Time (FILTER_RELEASE)
    36: 'sweep_shape', // Sweep Shape (FILTER_BETA)
    39: 'emphasis', // Emphasis (FILTER_EMPH)
  },
  tremolo: {
    14: 'duty', // Duty (TREMOLO_DUTY)
    19: 'start_phase', // Start Phase (TREMOLO_STARTPHASE)
    21: 'crossover_freq', // Crossover Freq (TREMOLO_XOVER)
    22: 'trigger_threshold', // Trigger Threshold (TREMOLO_THRESH)
    23: 'shape', // Shape (TREMOLO_BETA)
  },
  enhancer: {
    16: 'pan_left', // Pan Left (ENHANCER_PANL)
    17: 'pan_right', // Pan Right (ENHANCER_PANR)
  },
} as const;

export const GENERATED_PARAM_NAMES_FIRMWARE = 'AM4-Edit Mar 20 2026 build';
